# Generated SBE (Simple Binary Encoding) message codec
# Code generated by SBE. DO NOT EDIT.

abstract type DiagonalMatrixMessage{T} end

struct DiagonalMatrixMessageDecoder{T<:AbstractArray{UInt8}} <: DiagonalMatrixMessage{T}
    buffer::T
    offset::Int64
    position_ptr::Base.RefValue{Int64}
    acting_block_length::Int64
    acting_version::Int64
end

struct DiagonalMatrixMessageEncoder{T<:AbstractArray{UInt8}} <: DiagonalMatrixMessage{T}
    buffer::T
    offset::Int64
    position_ptr::Base.RefValue{Int64}
end

@inline function DiagonalMatrixMessageDecoder(context::SbeCodecContext, buffer, offset,
    acting_block_length, acting_version)
    sbe_position!(context, offset + acting_block_length)
    DiagonalMatrixMessageDecoder(buffer, offset, sbe_position_ptr(context), acting_block_length, acting_version)
end

@inline function DiagonalMatrixMessageDecoder(context::SbeCodecContext, buffer, offset, hdr::MessageHeader)
    DiagonalMatrixMessageDecoder(context, buffer, offset + sbe_encoded_length(hdr),
        Int64(blockLength(hdr)), Int64(version(hdr)))
end

@inline function DiagonalMatrixMessageDecoder(context::SbeCodecContext, buffer, hdr::MessageHeader)
    DiagonalMatrixMessageDecoder(context, buffer, 0, hdr)
end
@inline function DiagonalMatrixMessageDecoder(buffer, offset, acting_block_length, acting_version)
    DiagonalMatrixMessageDecoder(SbeCodecContext(), buffer, offset, acting_block_length, acting_version)
end

@inline DiagonalMatrixMessageDecoder(buffer, offset, hdr) = DiagonalMatrixMessageDecoder(SbeCodecContext(), buffer, offset, hdr)
@inline DiagonalMatrixMessageDecoder(buffer, hdr) = DiagonalMatrixMessageDecoder(SbeCodecContext(), buffer, 0, hdr)
 @inline function DiagonalMatrixMessageEncoder(context::SbeCodecContext, buffer, offset=0)
    sbe_position!(context, offset + 68)
    DiagonalMatrixMessageEncoder(buffer, offset, sbe_position_ptr(context))
end
@inline DiagonalMatrixMessageEncoder(buffer, offset=0) = DiagonalMatrixMessageEncoder(SbeCodecContext(), buffer, offset)
@inline DiagonalMatrixMessage() = DiagonalMatrixMessageEncoder(SbeCodecContext(), UInt8[])

@inline function DiagonalMatrixMessageEncoder(context::SbeCodecContext, buffer, offset, hdr::MessageHeader)
    blockLength!(hdr, 68)
    templateId!(hdr, 4)
    schemaId!(hdr, 1)
    version!(hdr, 0)
    DiagonalMatrixMessageEncoder(context, buffer, offset + sbe_encoded_length(hdr))
end

@inline function DiagonalMatrixMessageEncoder(context::SbeCodecContext, buffer, hdr::MessageHeader)
    DiagonalMatrixMessageEncoder(context, buffer, 0, hdr)
end

@inline function DiagonalMatrixMessageEncoder(buffer, offset, hdr::MessageHeader)
    DiagonalMatrixMessageEncoder(SbeCodecContext(), buffer, offset, hdr)
end

@inline function DiagonalMatrixMessageEncoder(buffer, hdr::MessageHeader)
    DiagonalMatrixMessageEncoder(SbeCodecContext(), buffer, 0, hdr)
end

sbe_buffer(m::DiagonalMatrixMessage) = m.buffer
sbe_offset(m::DiagonalMatrixMessage) = m.offset
sbe_position_ptr(m::DiagonalMatrixMessage) = m.position_ptr
sbe_position(m::DiagonalMatrixMessage) = m.position_ptr[]
@inline sbe_check_position(m::DiagonalMatrixMessage, position) = (checkbounds(m.buffer, position + 1); position)
@inline sbe_position!(m::DiagonalMatrixMessage, position) = m.position_ptr[] = position
sbe_block_length(::DiagonalMatrixMessage) = 68
sbe_template_id(::DiagonalMatrixMessage) = 4
sbe_schema_id(::DiagonalMatrixMessage) = 1
sbe_schema_version(::DiagonalMatrixMessage) = 0
sbe_semantic_type(::DiagonalMatrixMessage) = ""
sbe_semantic_version(::DiagonalMatrixMessage) = ""
sbe_encoded_length(m::DiagonalMatrixMessageEncoder) = sbe_position(m) - m.offset
sbe_rewind!(m::DiagonalMatrixMessageEncoder) = sbe_position!(m, m.offset + 68)

sbe_acting_block_length(m::DiagonalMatrixMessageDecoder) = m.acting_block_length
sbe_acting_version(m::DiagonalMatrixMessageDecoder) = m.acting_version
sbe_rewind!(m::DiagonalMatrixMessageDecoder) = sbe_position!(m, m.offset + m.acting_block_length)

@inline function sbe_decoded_length(m::DiagonalMatrixMessageDecoder)
    skipper = DiagonalMatrixMessageEncoder(m.buffer, m.offset)
    skip!(skipper)
    return sbe_encoded_length(skipper)
end

function sbe_decoded_buffer(m::DiagonalMatrixMessageDecoder)
    offset = m.offset - sbe_encoded_length(MessageHeader())
    offset < 0 && throw(ArgumentError("Message offset is negative"))
    return view(m.buffer, offset+1:offset+sbe_decoded_length(m))
end

function sbe_encoded_buffer(m::DiagonalMatrixMessageEncoder)
    offset = m.offset - sbe_encoded_length(MessageHeader())
    offset < 0 && throw(ArgumentError("Message offset is negative"))
    d = DiagonalMatrixMessageDecoder(m.buffer, MessageHeader(m.buffer, offset))
    return view(d.buffer, offset+1:offset+sbe_decoded_length(d))
end

function header_meta_attribute(::DiagonalMatrixMessage, meta_attribute)
    meta_attribute === :presence && return Symbol("required")
    error(lazy"unknown attribute: $meta_attribute")
end
header_id(::DiagonalMatrixMessage) = 1
header_since_version(::DiagonalMatrixMessage) = 0
header_in_acting_version(m::DiagonalMatrixMessage) = sbe_acting_version(m) >= 0
header_encoding_offset(::DiagonalMatrixMessage) = 0
header(m::DiagonalMatrixMessage) = SpidersMessageHeader(m.buffer, m.offset + 0)

function format_meta_attribute(::DiagonalMatrixMessage, meta_attribute)
    meta_attribute === :presence && return Symbol("required")
    error(lazy"unknown attribute: $meta_attribute")
end
format_id(::DiagonalMatrixMessage) = 2
format_since_version(::DiagonalMatrixMessage) = 0
format_in_acting_version(m::DiagonalMatrixMessage) = sbe_acting_version(m) >= 0
format_encoding_offset(::DiagonalMatrixMessage) = 64
format_encoding_length(::DiagonalMatrixMessage) = 1
@inline function format(::Type{Integer}, m::DiagonalMatrixMessageDecoder)
    return decode_le(Int8, m.buffer, m.offset + 64)
end
@inline function format(m::DiagonalMatrixMessageDecoder)
    return Format.SbeEnum(decode_le(Int8, m.buffer, m.offset + 64))
end
@inline format!(m::DiagonalMatrixMessageEncoder, value::Format.SbeEnum) = encode_le(Int8, m.buffer, m.offset + 64, Int8(value))

function indiciesFormat_meta_attribute(::DiagonalMatrixMessage, meta_attribute)
    meta_attribute === :presence && return Symbol("required")
    error(lazy"unknown attribute: $meta_attribute")
end
indiciesFormat_id(::DiagonalMatrixMessage) = 3
indiciesFormat_since_version(::DiagonalMatrixMessage) = 0
indiciesFormat_in_acting_version(m::DiagonalMatrixMessage) = sbe_acting_version(m) >= 0
indiciesFormat_encoding_offset(::DiagonalMatrixMessage) = 65
indiciesFormat_encoding_length(::DiagonalMatrixMessage) = 1
@inline function indiciesFormat(::Type{Integer}, m::DiagonalMatrixMessageDecoder)
    return decode_le(Int8, m.buffer, m.offset + 65)
end
@inline function indiciesFormat(m::DiagonalMatrixMessageDecoder)
    return Format.SbeEnum(decode_le(Int8, m.buffer, m.offset + 65))
end
@inline indiciesFormat!(m::DiagonalMatrixMessageEncoder, value::Format.SbeEnum) = encode_le(Int8, m.buffer, m.offset + 65, Int8(value))

function reserved1_meta_attribute(::DiagonalMatrixMessage, meta_attribute)
    meta_attribute === :presence && return Symbol("required")
    error(lazy"unknown attribute: $meta_attribute")
end
reserved1_id(::DiagonalMatrixMessage) = 10
reserved1_since_version(::DiagonalMatrixMessage) = 0
reserved1_in_acting_version(m::DiagonalMatrixMessage) = sbe_acting_version(m) >= 0
reserved1_encoding_offset(::DiagonalMatrixMessage) = 66
reserved1_null_value(::DiagonalMatrixMessage) = Int8(-128)
reserved1_min_value(::DiagonalMatrixMessage) = Int8(-127)
reserved1_max_value(::DiagonalMatrixMessage) = Int8(127)
reserved1_encoding_length(::DiagonalMatrixMessage) = 2
reserved1_length(::DiagonalMatrixMessage) = 2
reserved1_eltype(::DiagonalMatrixMessage) = Int8

@inline function reserved1(m::DiagonalMatrixMessageDecoder)
    return mappedarray(ltoh, reinterpret(Int8, view(m.buffer, m.offset+66+1:m.offset+66+sizeof(Int8)*2)))
end

@inline function reserved1(::Type{<:SVector},m::DiagonalMatrixMessageDecoder)
    return mappedarray(ltoh, reinterpret(SVector{2,Int8}, view(m.buffer, m.offset+66+1:m.offset+66+sizeof(Int8)*2))[])
end

@inline function reserved1!(m::DiagonalMatrixMessageEncoder)
    return mappedarray(ltoh, htol, reinterpret(Int8, view(m.buffer, m.offset+66+1:m.offset+66+sizeof(Int8)*2)))
end

@inline function reserved1!(m::DiagonalMatrixMessageEncoder, value)
    copyto!(mappedarray(ltoh, htol, reinterpret(Int8, view(m.buffer, m.offset+66+1:m.offset+66+sizeof(Int8)*2))), value)
end

function shape_meta_attribute(::DiagonalMatrixMessage, meta_attribute)
    meta_attribute === :semantic_type && return Symbol("int64")
    meta_attribute === :presence && return Symbol("required")
    error(lazy"unknown attribute: $meta_attribute")
end

shape_character_encoding(::DiagonalMatrixMessage) = "null"
shape_in_acting_version(m::DiagonalMatrixMessage) = sbe_acting_version(m) >= 0
shape_id(::DiagonalMatrixMessage) = 20
shape_header_length(::DiagonalMatrixMessage) = 4

@inline function shape_length(m::DiagonalMatrixMessage)
    return decode_le(UInt32, m.buffer, sbe_position(m))
end

@inline function shape_length!(m::DiagonalMatrixMessageEncoder, n)
    if !checkbounds(Bool, m.buffer, sbe_position(m) + 1 + 4 + n)
        error("buffer too short for data length")
    end
    return encode_le(UInt32, m.buffer, sbe_position(m), n)
end

@inline function skip_shape!(m::DiagonalMatrixMessage)
    len = shape_length(m)
    pos = sbe_position(m) + len + 4
    sbe_position!(m, pos)
    return len
end

@inline function shape(m::DiagonalMatrixMessageDecoder)
    len = shape_length(m)
    pos = sbe_position(m) + 4
    sbe_position!(m, pos + len)
    return view(m.buffer, pos+1:pos+len)
end

@inline function shape!(m::DiagonalMatrixMessageEncoder, len::Int)
    shape_length!(m, len)
    pos = sbe_position(m) + 4
    sbe_position!(m, pos + len)
    return view(m.buffer, pos+1:pos+len)
end

@inline function shape!(m::DiagonalMatrixMessageEncoder, src)
    len = Base.length(src)
    shape_length!(m, len)
    pos = sbe_position(m) + 4
    sbe_position!(m, pos + len)
    dest = view(m.buffer, pos+1:pos+len)
    copyto!(dest, src)
end

function values_meta_attribute(::DiagonalMatrixMessage, meta_attribute)
    meta_attribute === :presence && return Symbol("required")
    error(lazy"unknown attribute: $meta_attribute")
end

values_character_encoding(::DiagonalMatrixMessage) = "null"
values_in_acting_version(m::DiagonalMatrixMessage) = sbe_acting_version(m) >= 0
values_id(::DiagonalMatrixMessage) = 30
values_header_length(::DiagonalMatrixMessage) = 4

@inline function values_length(m::DiagonalMatrixMessage)
    return decode_le(UInt32, m.buffer, sbe_position(m))
end

@inline function values_length!(m::DiagonalMatrixMessageEncoder, n)
    if !checkbounds(Bool, m.buffer, sbe_position(m) + 1 + 4 + n)
        error("buffer too short for data length")
    end
    return encode_le(UInt32, m.buffer, sbe_position(m), n)
end

@inline function skip_values!(m::DiagonalMatrixMessage)
    len = values_length(m)
    pos = sbe_position(m) + len + 4
    sbe_position!(m, pos)
    return len
end

@inline function values(m::DiagonalMatrixMessageDecoder)
    len = values_length(m)
    pos = sbe_position(m) + 4
    sbe_position!(m, pos + len)
    return view(m.buffer, pos+1:pos+len)
end

@inline function values!(m::DiagonalMatrixMessageEncoder, len::Int)
    values_length!(m, len)
    pos = sbe_position(m) + 4
    sbe_position!(m, pos + len)
    return view(m.buffer, pos+1:pos+len)
end

@inline function values!(m::DiagonalMatrixMessageEncoder, src)
    len = Base.length(src)
    values_length!(m, len)
    pos = sbe_position(m) + 4
    sbe_position!(m, pos + len)
    dest = view(m.buffer, pos+1:pos+len)
    copyto!(dest, src)
end

function Base.show(io::IO, m::DiagonalMatrixMessage{T}) where {T}
    println(io, "DiagonalMatrixMessage view over a type $T")
    println(io, "SbeBlockLength: ", sbe_block_length(m))
    println(io, "SbeTemplateId:  ", sbe_template_id(m))
    println(io, "SbeSchemaId:    ", sbe_schema_id(m))
    println(io, "SbeSchemaVersion: ", sbe_schema_version(m))

    writer = DiagonalMatrixMessageDecoder(sbe_buffer(m), sbe_offset(m), sbe_block_length(m), sbe_schema_version(m))
    print(io, "header: ")
    Base.show(io, header(writer))

    println(io)
    print(io, "format: ")
    print(io, format(writer))

    println(io)
    print(io, "indiciesFormat: ")
    print(io, indiciesFormat(writer))

    println(io)
    print(io, "reserved1: ")
    print(io, reserved1(writer))

    println(io)
    print(io, "shape: ")
    print(io, skip_shape!(writer))
    print(io, " bytes of raw data")

    println(io)
    print(io, "values: ")
    print(io, skip_values!(writer))
    print(io, " bytes of raw data")

    nothing
end

@inline function skip!(m::DiagonalMatrixMessage)
    skip_shape!(m)
    skip_values!(m)
    return
end
