# Generated SBE (Simple Binary Encoding) message codec
# Code generated by SBE. DO NOT EDIT.

struct DiagonalMatrixMessage{T<:AbstractArray{UInt8}}
    buffer::T
    offset::Int64
    position_ptr::Base.RefValue{Int64}
    acting_block_length::Int64
    acting_version::Int64
end

@inline function DiagonalMatrixMessage(context::SbeCodecContext, buffer, offset, acting_block_length, acting_version)
    sbe_position!(context, offset + acting_block_length)
    return DiagonalMatrixMessage(buffer, offset, sbe_position_ptr(context), acting_block_length, acting_version)
end
@inline DiagonalMatrixMessage() = DiagonalMatrixMessage(SbeCodecContext(), UInt8[], 0, 0, 0)

@inline function DiagonalMatrixMessageDecoder(context::SbeCodecContext, buffer, offset,
    acting_block_length, acting_version)
    return DiagonalMatrixMessage(context, buffer, offset, acting_block_length, acting_version)
end

@inline function DiagonalMatrixMessageDecoder(context::SbeCodecContext, buffer, offset, hdr::MessageHeader)
    return DiagonalMatrixMessageDecoder(context, buffer, offset + sbe_encoded_length(hdr),
        Int64(blockLength(hdr)), Int64(version(hdr)))
end

@inline function DiagonalMatrixMessageDecoder(context::SbeCodecContext, buffer, hdr::MessageHeader)
    return DiagonalMatrixMessageDecoder(context, buffer, 0, hdr)
end

@inline function DiagonalMatrixMessageEncoder(context::SbeCodecContext, buffer, offset=0)
    return DiagonalMatrixMessage(context, buffer, offset, 68, 0)
end

@inline function DiagonalMatrixMessageEncoder(context::SbeCodecContext, buffer, offset, hdr::MessageHeader)
    blockLength!(hdr, 68)
    templateId!(hdr, 4)
    schemaId!(hdr, 1)
    version!(hdr, 0)
    return DiagonalMatrixMessage(context, buffer, offset + sbe_encoded_length(hdr), 68, 0)
end

@inline function DiagonalMatrixMessageEncoder(context::SbeCodecContext, buffer, hdr::MessageHeader)
    return DiagonalMatrixMessageEncoder(context, buffer, 0, hdr)
end

sbe_buffer(m::DiagonalMatrixMessage) = @inbounds view(m.buffer, m.offset+1:m.offset+sbe_decoded_length(m))
sbe_offset(m::DiagonalMatrixMessage) = m.offset
sbe_position_ptr(m::DiagonalMatrixMessage) = m.position_ptr
sbe_acting_block_length(m::DiagonalMatrixMessage) = m.acting_block_length
sbe_acting_version(m::DiagonalMatrixMessage) = m.acting_version
sbe_position(m::DiagonalMatrixMessage) = m.position_ptr[]
@inline sbe_check_position(m::DiagonalMatrixMessage, position) = (checkbounds(m.buffer, position + 1); position)
@inline sbe_position!(m::DiagonalMatrixMessage, position) = m.position_ptr[] = sbe_check_position(m, position)
sbe_block_length(::DiagonalMatrixMessage) = 68
sbe_template_id(::DiagonalMatrixMessage) = 4
sbe_schema_id(::DiagonalMatrixMessage) = 1
sbe_schema_version(::DiagonalMatrixMessage) = 0
sbe_semantic_type(::DiagonalMatrixMessage) = ""
sbe_semantic_version(::DiagonalMatrixMessage) = ""
sbe_rewind!(m::DiagonalMatrixMessage) = (sbe_position!(m, m.offset + m.acting_block_length); m)
sbe_encoded_length(m::DiagonalMatrixMessage) = sbe_position(m) - m.offset
@inline function sbe_decoded_length(m::DiagonalMatrixMessage)
    skipper = DiagonalMatrixMessage(SbeCodecContext(), m.buffer, m.offset, 68, sbe_acting_version(m))
    skip!(skipper)
    return sbe_encoded_length(skipper)
end

function header_meta_attribute(::DiagonalMatrixMessage, meta_attribute)
    meta_attribute === :presence && return Symbol("required")
    error(lazy"unknown attribute: $meta_attribute")
end
header_id(::DiagonalMatrixMessage) = 1
header_in_acting_version(m::DiagonalMatrixMessage) = sbe_acting_version(m) >= 0
header_encoding_offset(::DiagonalMatrixMessage) = 0
header(m::DiagonalMatrixMessage) = SpidersMessageHeader(m.buffer, m.offset + 0)

function format_meta_attribute(::DiagonalMatrixMessage, meta_attribute)
    meta_attribute === :presence && return Symbol("required")
    error(lazy"unknown attribute: $meta_attribute")
end
format_id(::DiagonalMatrixMessage) = 2
format_in_acting_version(m::DiagonalMatrixMessage) = sbe_acting_version(m) >= 0
format_encoding_offset(::DiagonalMatrixMessage) = 64
format_encoding_length(::DiagonalMatrixMessage) = 1
@inline function format_raw(m::DiagonalMatrixMessage)
    return decode_le(Int8, m.buffer, m.offset + 64)
end
@inline function format(m::DiagonalMatrixMessage)
    return Format.SbeEnum(decode_le(Int8, m.buffer, m.offset + 64))
end
@inline format!(m::DiagonalMatrixMessage, value::Format.SbeEnum) = encode_le(Int8, m.buffer, m.offset + 64, Int8(value))

function indiciesFormat_meta_attribute(::DiagonalMatrixMessage, meta_attribute)
    meta_attribute === :presence && return Symbol("required")
    error(lazy"unknown attribute: $meta_attribute")
end
indiciesFormat_id(::DiagonalMatrixMessage) = 3
indiciesFormat_in_acting_version(m::DiagonalMatrixMessage) = sbe_acting_version(m) >= 0
indiciesFormat_encoding_offset(::DiagonalMatrixMessage) = 65
indiciesFormat_encoding_length(::DiagonalMatrixMessage) = 1
@inline function indiciesFormat_raw(m::DiagonalMatrixMessage)
    return decode_le(Int8, m.buffer, m.offset + 65)
end
@inline function indiciesFormat(m::DiagonalMatrixMessage)
    return Format.SbeEnum(decode_le(Int8, m.buffer, m.offset + 65))
end
@inline indiciesFormat!(m::DiagonalMatrixMessage, value::Format.SbeEnum) = encode_le(Int8, m.buffer, m.offset + 65, Int8(value))

function reserved1_meta_attribute(::DiagonalMatrixMessage, meta_attribute)
    meta_attribute === :presence && return Symbol("required")
    error(lazy"unknown attribute: $meta_attribute")
end
reserved1_id(::DiagonalMatrixMessage) = 10
reserved1_in_acting_version(m::DiagonalMatrixMessage) = sbe_acting_version(m) >= 0
reserved1_encoding_offset(::DiagonalMatrixMessage) = 66
reserved1_null_value(::DiagonalMatrixMessage) = Int8(-128)
reserved1_min_value(::DiagonalMatrixMessage) = Int8(-127)
reserved1_max_value(::DiagonalMatrixMessage) = Int8(127)
reserved1_encoding_length(::DiagonalMatrixMessage) = 2
reserved1_length(::DiagonalMatrixMessage) = 2
reserved1_eltype(::DiagonalMatrixMessage) = Int8

@inline function reserved1(m::DiagonalMatrixMessage)
    return @inbounds mappedarray(ltoh, htol, reinterpret(Int8, view(m.buffer, m.offset+66+1:m.offset+66+sizeof(Int8)*2)))
end

@inline function reserved1_static(m::DiagonalMatrixMessage)
    return @inbounds mappedarray(ltoh, reinterpret(SVector{2,Int8}, view(m.buffer, m.offset+66+1:m.offset+66+sizeof(Int8)*2))[])
end

@inline function reserved1!(m::DiagonalMatrixMessage, value)
    copyto!(mappedarray(ltoh, htol, reinterpret(Int8, view(m.buffer, m.offset+66+1:m.offset+66+sizeof(Int8)*2))), value)
end

function shape_meta_attribute(::DiagonalMatrixMessage, meta_attribute)
    meta_attribute === :semantic_type && return Symbol("int64")
    meta_attribute === :presence && return Symbol("required")
    error(lazy"unknown attribute: $meta_attribute")
end

shape_character_encoding(::DiagonalMatrixMessage) = "null"
shape_in_acting_version(m::DiagonalMatrixMessage) = sbe_acting_version(m) >= 0
shape_id(::DiagonalMatrixMessage) = 20
shape_header_length(::DiagonalMatrixMessage) = 4

@inline function shape_length(m::DiagonalMatrixMessage)
    return decode_le(UInt32, m.buffer, sbe_position(m))
end

@inline function shape_length!(m::DiagonalMatrixMessage, n)
    if !checkbounds(Bool, m.buffer, sbe_position(m) + 1 + 4 + n)
        error("buffer too short for data length")
    end
    return encode_le(UInt32, m.buffer, sbe_position(m), n)
end

@inline function skip_shape!(m::DiagonalMatrixMessage)
    len = shape_length(m)
    pos = sbe_position(m) + len + 4
    sbe_position!(m, pos)
    return len
end

@inline function shape(m::DiagonalMatrixMessage)
    len = shape_length(m)
    pos = sbe_position(m) + 4
    sbe_position!(m, pos + len)
    return @inbounds view(m.buffer, pos+1:pos+len)
end

@inline function shape!(m::DiagonalMatrixMessage, len::Int)
    shape_length!(m, len)
    pos = sbe_position(m) + 4
    sbe_position!(m, pos + len)
    return @inbounds view(m.buffer, pos+1:pos+len)
end

function values_meta_attribute(::DiagonalMatrixMessage, meta_attribute)
    meta_attribute === :presence && return Symbol("required")
    error(lazy"unknown attribute: $meta_attribute")
end

values_character_encoding(::DiagonalMatrixMessage) = "null"
values_in_acting_version(m::DiagonalMatrixMessage) = sbe_acting_version(m) >= 0
values_id(::DiagonalMatrixMessage) = 30
values_header_length(::DiagonalMatrixMessage) = 4

@inline function values_length(m::DiagonalMatrixMessage)
    return decode_le(UInt32, m.buffer, sbe_position(m))
end

@inline function values_length!(m::DiagonalMatrixMessage, n)
    if !checkbounds(Bool, m.buffer, sbe_position(m) + 1 + 4 + n)
        error("buffer too short for data length")
    end
    return encode_le(UInt32, m.buffer, sbe_position(m), n)
end

@inline function skip_values!(m::DiagonalMatrixMessage)
    len = values_length(m)
    pos = sbe_position(m) + len + 4
    sbe_position!(m, pos)
    return len
end

@inline function values(m::DiagonalMatrixMessage)
    len = values_length(m)
    pos = sbe_position(m) + 4
    sbe_position!(m, pos + len)
    return @inbounds view(m.buffer, pos+1:pos+len)
end

@inline function values!(m::DiagonalMatrixMessage, len::Int)
    values_length!(m, len)
    pos = sbe_position(m) + 4
    sbe_position!(m, pos + len)
    return @inbounds view(m.buffer, pos+1:pos+len)
end

function print_fields(io::IO, writer::DiagonalMatrixMessage{T}) where {T}
    println(io, "DiagonalMatrixMessage view over a type $T")
    println(io, "SbeBlockLength: ", sbe_block_length(writer))
    println(io, "SbeTemplateId:  ", sbe_template_id(writer))
    println(io, "SbeSchemaId:    ", sbe_schema_id(writer))
    println(io, "SbeSchemaVersion: ", sbe_schema_version(writer))

    sbe_rewind!(writer)
    print(io, "header: ")
    print_fields(io, header(writer))

    println(io)
    print(io, "format: ")
    print(io, format(writer))

    println(io)
    print(io, "indiciesFormat: ")
    print(io, indiciesFormat(writer))

    println(io)
    print(io, "reserved1: ")
    print(io, reserved1(writer))

    println(io)
    print(io, "shape: ")
    print(io, skip_shape!(writer))
    print(io, " bytes of raw data")

    println(io)
    print(io, "values: ")
    print(io, skip_values!(writer))
    print(io, " bytes of raw data")

    sbe_rewind!(writer)
    nothing
end

@inline function skip!(m::DiagonalMatrixMessage)
    skip_shape!(m)
    skip_values!(m)
    return
end
