# Generated SBE (Simple Binary Encoding) message codec
# Code generated by SBE. DO NOT EDIT.

struct SparseMatrixCSXMessage{T<:AbstractArray{UInt8}}
    buffer::T
    offset::Int64
    position_ptr::Base.RefValue{Int64}
    acting_block_length::Int64
    acting_version::Int64
end

@inline function SparseMatrixCSXMessage(context::SbeCodecContext, buffer, offset, acting_block_length, acting_version)
    sbe_position!(context, offset + acting_block_length)
    return SparseMatrixCSXMessage(buffer, offset, sbe_position_ptr(context), acting_block_length, acting_version)
end
@inline SparseMatrixCSXMessage() = SparseMatrixCSXMessage(SbeCodecContext(), UInt8[], 0, 0, 0)

@inline function SparseMatrixCSXMessageDecoder(context::SbeCodecContext, buffer, offset,
    acting_block_length, acting_version)
    return SparseMatrixCSXMessage(context, buffer, offset, acting_block_length, acting_version)
end

@inline function SparseMatrixCSXMessageDecoder(context::SbeCodecContext, buffer, offset, hdr::MessageHeader)
    return SparseMatrixCSXMessageDecoder(context, buffer, offset + sbe_encoded_length(hdr),
        Int64(blockLength(hdr)), Int64(version(hdr)))
end

@inline function SparseMatrixCSXMessageDecoder(context::SbeCodecContext, buffer, hdr::MessageHeader)
    return SparseMatrixCSXMessageDecoder(context, buffer, 0, hdr)
end

@inline function SparseMatrixCSXMessageEncoder(context::SbeCodecContext, buffer, offset=0)
    return SparseMatrixCSXMessage(context, buffer, offset, 84, 0)
end

@inline function SparseMatrixCSXMessageEncoder(context::SbeCodecContext, buffer, offset, hdr::MessageHeader)
    blockLength!(hdr, 84)
    templateId!(hdr, 2)
    schemaId!(hdr, 1)
    version!(hdr, 0)
    return SparseMatrixCSXMessage(context, buffer, offset + sbe_encoded_length(hdr), 84, 0)
end

@inline function SparseMatrixCSXMessageEncoder(context::SbeCodecContext, buffer, hdr::MessageHeader)
    return SparseMatrixCSXMessageEncoder(context, buffer, 0, hdr)
end

sbe_buffer(m::SparseMatrixCSXMessage) = @inbounds view(m.buffer, m.offset+1:m.offset+sbe_decoded_length(m))
sbe_offset(m::SparseMatrixCSXMessage) = m.offset
sbe_position_ptr(m::SparseMatrixCSXMessage) = m.position_ptr
sbe_acting_block_length(m::SparseMatrixCSXMessage) = m.acting_block_length
sbe_acting_version(m::SparseMatrixCSXMessage) = m.acting_version
sbe_position(m::SparseMatrixCSXMessage) = m.position_ptr[]
@inline sbe_check_position(m::SparseMatrixCSXMessage, position) = (checkbounds(m.buffer, position + 1); position)
@inline sbe_position!(m::SparseMatrixCSXMessage, position) = m.position_ptr[] = sbe_check_position(m, position)
sbe_block_length(::SparseMatrixCSXMessage) = 84
sbe_template_id(::SparseMatrixCSXMessage) = 2
sbe_schema_id(::SparseMatrixCSXMessage) = 1
sbe_schema_version(::SparseMatrixCSXMessage) = 0
sbe_semantic_type(::SparseMatrixCSXMessage) = ""
sbe_semantic_version(::SparseMatrixCSXMessage) = ""
sbe_rewind!(m::SparseMatrixCSXMessage) = (sbe_position!(m, m.offset + m.acting_block_length); m)
sbe_encoded_length(m::SparseMatrixCSXMessage) = sbe_position(m) - m.offset
@inline function sbe_decoded_length(m::SparseMatrixCSXMessage)
    skipper = SparseMatrixCSXMessage(SbeCodecContext(), m.buffer, m.offset, 84, sbe_acting_version(m))
    skip!(skipper)
    return sbe_encoded_length(skipper)
end

function header_meta_attribute(::SparseMatrixCSXMessage, meta_attribute)
    meta_attribute === :presence && return Symbol("required")
    error(lazy"unknown attribute: $meta_attribute")
end
header_id(::SparseMatrixCSXMessage) = 1
header_in_acting_version(m::SparseMatrixCSXMessage) = sbe_acting_version(m) >= 0
header_encoding_offset(::SparseMatrixCSXMessage) = 0
header(m::SparseMatrixCSXMessage) = SpidersMessageHeader(m.buffer, m.offset + 0)

function format_meta_attribute(::SparseMatrixCSXMessage, meta_attribute)
    meta_attribute === :presence && return Symbol("required")
    error(lazy"unknown attribute: $meta_attribute")
end
format_id(::SparseMatrixCSXMessage) = 2
format_in_acting_version(m::SparseMatrixCSXMessage) = sbe_acting_version(m) >= 0
format_encoding_offset(::SparseMatrixCSXMessage) = 64
format_encoding_length(::SparseMatrixCSXMessage) = 1
@inline function format_raw(m::SparseMatrixCSXMessage)
    return decode_le(Int8, m.buffer, m.offset + 64)
end
@inline function format(m::SparseMatrixCSXMessage)
    return Format.SbeEnum(decode_le(Int8, m.buffer, m.offset + 64))
end
@inline format!(m::SparseMatrixCSXMessage, value::Format.SbeEnum) = encode_le(Int8, m.buffer, m.offset + 64, Int8(value))

function order_meta_attribute(::SparseMatrixCSXMessage, meta_attribute)
    meta_attribute === :presence && return Symbol("required")
    error(lazy"unknown attribute: $meta_attribute")
end
order_id(::SparseMatrixCSXMessage) = 3
order_in_acting_version(m::SparseMatrixCSXMessage) = sbe_acting_version(m) >= 0
order_encoding_offset(::SparseMatrixCSXMessage) = 65
order_encoding_length(::SparseMatrixCSXMessage) = 1
@inline function order_raw(m::SparseMatrixCSXMessage)
    return decode_le(Int8, m.buffer, m.offset + 65)
end
@inline function order(m::SparseMatrixCSXMessage)
    return Order.SbeEnum(decode_le(Int8, m.buffer, m.offset + 65))
end
@inline order!(m::SparseMatrixCSXMessage, value::Order.SbeEnum) = encode_le(Int8, m.buffer, m.offset + 65, Int8(value))

function indexing_meta_attribute(::SparseMatrixCSXMessage, meta_attribute)
    meta_attribute === :presence && return Symbol("required")
    error(lazy"unknown attribute: $meta_attribute")
end
indexing_id(::SparseMatrixCSXMessage) = 4
indexing_in_acting_version(m::SparseMatrixCSXMessage) = sbe_acting_version(m) >= 0
indexing_encoding_offset(::SparseMatrixCSXMessage) = 66
indexing_encoding_length(::SparseMatrixCSXMessage) = 1
@inline function indexing_raw(m::SparseMatrixCSXMessage)
    return decode_le(Int8, m.buffer, m.offset + 66)
end
@inline function indexing(m::SparseMatrixCSXMessage)
    return Indexing.SbeEnum(decode_le(Int8, m.buffer, m.offset + 66))
end
@inline indexing!(m::SparseMatrixCSXMessage, value::Indexing.SbeEnum) = encode_le(Int8, m.buffer, m.offset + 66, Int8(value))

function reserved1_meta_attribute(::SparseMatrixCSXMessage, meta_attribute)
    meta_attribute === :presence && return Symbol("required")
    error(lazy"unknown attribute: $meta_attribute")
end
reserved1_id(::SparseMatrixCSXMessage) = 5
reserved1_in_acting_version(m::SparseMatrixCSXMessage) = sbe_acting_version(m) >= 0
reserved1_encoding_offset(::SparseMatrixCSXMessage) = 67
reserved1_null_value(::SparseMatrixCSXMessage) = Int8(-128)
reserved1_min_value(::SparseMatrixCSXMessage) = Int8(-127)
reserved1_max_value(::SparseMatrixCSXMessage) = Int8(127)
reserved1_encoding_length(::SparseMatrixCSXMessage) = 1

@inline function reserved1(m::SparseMatrixCSXMessage)
    return decode_le(Int8, m.buffer, m.offset + 67)
end
@inline reserved1!(m::SparseMatrixCSXMessage, value) = encode_le(Int8, m.buffer, m.offset + 67, value)

function shape_meta_attribute(::SparseMatrixCSXMessage, meta_attribute)
    meta_attribute === :presence && return Symbol("required")
    error(lazy"unknown attribute: $meta_attribute")
end
shape_id(::SparseMatrixCSXMessage) = 6
shape_in_acting_version(m::SparseMatrixCSXMessage) = sbe_acting_version(m) >= 0
shape_encoding_offset(::SparseMatrixCSXMessage) = 68
shape_null_value(::SparseMatrixCSXMessage) = Int64(-9223372036854775808)
shape_min_value(::SparseMatrixCSXMessage) = Int64(-9223372036854775807)
shape_max_value(::SparseMatrixCSXMessage) = Int64(9223372036854775807)
shape_encoding_length(::SparseMatrixCSXMessage) = 16
shape_length(::SparseMatrixCSXMessage) = 2
shape_eltype(::SparseMatrixCSXMessage) = Int64

@inline function shape(m::SparseMatrixCSXMessage)
    return @inbounds mappedarray(ltoh, htol, reinterpret(Int64, view(m.buffer, m.offset+68+1:m.offset+68+sizeof(Int64)*2)))
end

@inline function shape_static(m::SparseMatrixCSXMessage)
    return @inbounds mappedarray(ltoh, reinterpret(SVector{2,Int64}, view(m.buffer, m.offset+68+1:m.offset+68+sizeof(Int64)*2))[])
end

@inline function shape!(m::SparseMatrixCSXMessage, value)
    copyto!(mappedarray(ltoh, htol, reinterpret(Int64, view(m.buffer, m.offset+68+1:m.offset+68+sizeof(Int64)*2))), value)
end

function indexPointer_meta_attribute(::SparseMatrixCSXMessage, meta_attribute)
    meta_attribute === :semantic_type && return Symbol("int64")
    meta_attribute === :presence && return Symbol("required")
    error(lazy"unknown attribute: $meta_attribute")
end

indexPointer_character_encoding(::SparseMatrixCSXMessage) = "null"
indexPointer_in_acting_version(m::SparseMatrixCSXMessage) = sbe_acting_version(m) >= 0
indexPointer_id(::SparseMatrixCSXMessage) = 20
indexPointer_header_length(::SparseMatrixCSXMessage) = 4

@inline function indexPointer_length(m::SparseMatrixCSXMessage)
    return decode_le(UInt32, m.buffer, sbe_position(m))
end

@inline function indexPointer_length!(m::SparseMatrixCSXMessage, n)
    if !checkbounds(Bool, m.buffer, sbe_position(m) + 1 + 4 + n)
        error("buffer too short for data length")
    end
    return encode_le(UInt32, m.buffer, sbe_position(m), n)
end

@inline function skip_indexPointer!(m::SparseMatrixCSXMessage)
    len = indexPointer_length(m)
    pos = sbe_position(m) + len + 4
    sbe_position!(m, pos)
    return len
end

@inline function indexPointer(m::SparseMatrixCSXMessage)
    len = indexPointer_length(m)
    pos = sbe_position(m) + 4
    sbe_position!(m, pos + len)
    return @inbounds view(m.buffer, pos+1:pos+len)
end

@inline function indexPointer!(m::SparseMatrixCSXMessage, len::Int)
    indexPointer_length!(m, len)
    pos = sbe_position(m) + 4
    sbe_position!(m, pos + len)
    return @inbounds view(m.buffer, pos+1:pos+len)
end

function indicies_meta_attribute(::SparseMatrixCSXMessage, meta_attribute)
    meta_attribute === :semantic_type && return Symbol("int64")
    meta_attribute === :presence && return Symbol("required")
    error(lazy"unknown attribute: $meta_attribute")
end

indicies_character_encoding(::SparseMatrixCSXMessage) = "null"
indicies_in_acting_version(m::SparseMatrixCSXMessage) = sbe_acting_version(m) >= 0
indicies_id(::SparseMatrixCSXMessage) = 21
indicies_header_length(::SparseMatrixCSXMessage) = 4

@inline function indicies_length(m::SparseMatrixCSXMessage)
    return decode_le(UInt32, m.buffer, sbe_position(m))
end

@inline function indicies_length!(m::SparseMatrixCSXMessage, n)
    if !checkbounds(Bool, m.buffer, sbe_position(m) + 1 + 4 + n)
        error("buffer too short for data length")
    end
    return encode_le(UInt32, m.buffer, sbe_position(m), n)
end

@inline function skip_indicies!(m::SparseMatrixCSXMessage)
    len = indicies_length(m)
    pos = sbe_position(m) + len + 4
    sbe_position!(m, pos)
    return len
end

@inline function indicies(m::SparseMatrixCSXMessage)
    len = indicies_length(m)
    pos = sbe_position(m) + 4
    sbe_position!(m, pos + len)
    return @inbounds view(m.buffer, pos+1:pos+len)
end

@inline function indicies!(m::SparseMatrixCSXMessage, len::Int)
    indicies_length!(m, len)
    pos = sbe_position(m) + 4
    sbe_position!(m, pos + len)
    return @inbounds view(m.buffer, pos+1:pos+len)
end

function values_meta_attribute(::SparseMatrixCSXMessage, meta_attribute)
    meta_attribute === :presence && return Symbol("required")
    error(lazy"unknown attribute: $meta_attribute")
end

values_character_encoding(::SparseMatrixCSXMessage) = "null"
values_in_acting_version(m::SparseMatrixCSXMessage) = sbe_acting_version(m) >= 0
values_id(::SparseMatrixCSXMessage) = 30
values_header_length(::SparseMatrixCSXMessage) = 4

@inline function values_length(m::SparseMatrixCSXMessage)
    return decode_le(UInt32, m.buffer, sbe_position(m))
end

@inline function values_length!(m::SparseMatrixCSXMessage, n)
    if !checkbounds(Bool, m.buffer, sbe_position(m) + 1 + 4 + n)
        error("buffer too short for data length")
    end
    return encode_le(UInt32, m.buffer, sbe_position(m), n)
end

@inline function skip_values!(m::SparseMatrixCSXMessage)
    len = values_length(m)
    pos = sbe_position(m) + len + 4
    sbe_position!(m, pos)
    return len
end

@inline function values(m::SparseMatrixCSXMessage)
    len = values_length(m)
    pos = sbe_position(m) + 4
    sbe_position!(m, pos + len)
    return @inbounds view(m.buffer, pos+1:pos+len)
end

@inline function values!(m::SparseMatrixCSXMessage, len::Int)
    values_length!(m, len)
    pos = sbe_position(m) + 4
    sbe_position!(m, pos + len)
    return @inbounds view(m.buffer, pos+1:pos+len)
end

function print_fields(io::IO, writer::SparseMatrixCSXMessage{T}) where {T}
    println(io, "SparseMatrixCSXMessage view over a type $T")
    println(io, "SbeBlockLength: ", sbe_block_length(writer))
    println(io, "SbeTemplateId:  ", sbe_template_id(writer))
    println(io, "SbeSchemaId:    ", sbe_schema_id(writer))
    println(io, "SbeSchemaVersion: ", sbe_schema_version(writer))

    sbe_rewind!(writer)
    print(io, "header: ")
    print_fields(io, header(writer))

    println(io)
    print(io, "format: ")
    print(io, format(writer))

    println(io)
    print(io, "order: ")
    print(io, order(writer))

    println(io)
    print(io, "indexing: ")
    print(io, indexing(writer))

    println(io)
    print(io, "reserved1: ")
    print(io, reserved1(writer))

    println(io)
    print(io, "shape: ")
    print(io, shape(writer))

    println(io)
    print(io, "indexPointer: ")
    print(io, skip_indexPointer!(writer))
    print(io, " bytes of raw data")

    println(io)
    print(io, "indicies: ")
    print(io, skip_indicies!(writer))
    print(io, " bytes of raw data")

    println(io)
    print(io, "values: ")
    print(io, skip_values!(writer))
    print(io, " bytes of raw data")

    sbe_rewind!(writer)
    nothing
end

@inline function skip!(m::SparseMatrixCSXMessage)
    skip_indexPointer!(m)
    skip_indicies!(m)
    skip_values!(m)
    return
end
