# Generated SBE (Simple Binary Encoding) message codec
# Code generated by SBE. DO NOT EDIT.

abstract type SparseVectorMessage{T} end

struct SparseVectorMessageDecoder{T<:AbstractArray{UInt8}} <: SparseVectorMessage{T}
    buffer::T
    offset::Int64
    position_ptr::Base.RefValue{Int64}
    acting_block_length::Int64
    acting_version::Int64
end

struct SparseVectorMessageEncoder{T<:AbstractArray{UInt8}} <: SparseVectorMessage{T}
    buffer::T
    offset::Int64
    position_ptr::Base.RefValue{Int64}
end

@inline function SparseVectorMessageDecoder(context::SbeCodecContext, buffer, offset,
    acting_block_length, acting_version)
    sbe_position!(context, offset + acting_block_length)
    SparseVectorMessageDecoder(buffer, offset, sbe_position_ptr(context), acting_block_length, acting_version)
end

@inline function SparseVectorMessageDecoder(context::SbeCodecContext, buffer, offset, hdr::MessageHeader)
    SparseVectorMessageDecoder(context, buffer, offset + sbe_encoded_length(hdr),
        Int64(blockLength(hdr)), Int64(version(hdr)))
end

@inline function SparseVectorMessageDecoder(context::SbeCodecContext, buffer, hdr::MessageHeader)
    SparseVectorMessageDecoder(context, buffer, 0, hdr)
end
@inline function SparseVectorMessageDecoder(buffer, offset, acting_block_length, acting_version)
    SparseVectorMessageDecoder(SbeCodecContext(), buffer, offset, acting_block_length, acting_version)
end

@inline SparseVectorMessageDecoder(buffer, offset, hdr) = SparseVectorMessageDecoder(SbeCodecContext(), buffer, offset, hdr)
@inline SparseVectorMessageDecoder(buffer, hdr) = SparseVectorMessageDecoder(SbeCodecContext(), buffer, 0, hdr)
 @inline function SparseVectorMessageEncoder(context::SbeCodecContext, buffer, offset=0)
    sbe_position!(context, offset + 76)
    SparseVectorMessageEncoder(buffer, offset, sbe_position_ptr(context))
end
@inline SparseVectorMessageEncoder(buffer, offset=0) = SparseVectorMessageEncoder(SbeCodecContext(), buffer, offset)
@inline SparseVectorMessage() = SparseVectorMessageEncoder(SbeCodecContext(), UInt8[])

@inline function SparseVectorMessageEncoder(context::SbeCodecContext, buffer, offset, hdr::MessageHeader)
    blockLength!(hdr, 76)
    templateId!(hdr, 3)
    schemaId!(hdr, 1)
    version!(hdr, 0)
    SparseVectorMessageEncoder(context, buffer, offset + sbe_encoded_length(hdr))
end

@inline function SparseVectorMessageEncoder(context::SbeCodecContext, buffer, hdr::MessageHeader)
    SparseVectorMessageEncoder(context, buffer, 0, hdr)
end

@inline function SparseVectorMessageEncoder(buffer, offset, hdr::MessageHeader)
    SparseVectorMessageEncoder(SbeCodecContext(), buffer, offset, hdr)
end

@inline function SparseVectorMessageEncoder(buffer, hdr::MessageHeader)
    SparseVectorMessageEncoder(SbeCodecContext(), buffer, 0, hdr)
end

sbe_buffer(m::SparseVectorMessage) = m.buffer
sbe_offset(m::SparseVectorMessage) = m.offset
sbe_position_ptr(m::SparseVectorMessage) = m.position_ptr
sbe_position(m::SparseVectorMessage) = m.position_ptr[]
@inline sbe_check_position(m::SparseVectorMessage, position) = (checkbounds(m.buffer, position + 1); position)
@inline sbe_position!(m::SparseVectorMessage, position) = m.position_ptr[] = position
sbe_block_length(::SparseVectorMessage) = 76
sbe_template_id(::SparseVectorMessage) = 3
sbe_schema_id(::SparseVectorMessage) = 1
sbe_schema_version(::SparseVectorMessage) = 0
sbe_semantic_type(::SparseVectorMessage) = ""
sbe_semantic_version(::SparseVectorMessage) = ""
sbe_encoded_length(m::SparseVectorMessageEncoder) = sbe_position(m) - m.offset
sbe_rewind!(m::SparseVectorMessageEncoder) = sbe_position!(m, m.offset + 76)

sbe_acting_block_length(m::SparseVectorMessageDecoder) = m.acting_block_length
sbe_acting_version(m::SparseVectorMessageDecoder) = m.acting_version
sbe_rewind!(m::SparseVectorMessageDecoder) = sbe_position!(m, m.offset + m.acting_block_length)

@inline function sbe_decoded_length(m::SparseVectorMessageDecoder)
    skipper = SparseVectorMessageEncoder(m.buffer, m.offset)
    skip!(skipper)
    return sbe_encoded_length(skipper)
end

function sbe_decoded_buffer(m::SparseVectorMessageDecoder)
    offset = m.offset - sbe_encoded_length(MessageHeader())
    offset < 0 && throw(ArgumentError("Message offset is negative"))
    return view(m.buffer, offset+1:offset+sbe_decoded_length(m))
end

function sbe_encoded_buffer(m::SparseVectorMessageEncoder)
    offset = m.offset - sbe_encoded_length(MessageHeader())
    offset < 0 && throw(ArgumentError("Message offset is negative"))
    d = SparseVectorMessageDecoder(m.buffer, MessageHeader(m.buffer, offset))
    return view(d.buffer, offset+1:offset+sbe_decoded_length(d))
end

function header_meta_attribute(::SparseVectorMessage, meta_attribute)
    meta_attribute === :presence && return Symbol("required")
    error(lazy"unknown attribute: $meta_attribute")
end
header_id(::SparseVectorMessage) = 1
header_since_version(::SparseVectorMessage) = 0
header_in_acting_version(m::SparseVectorMessage) = sbe_acting_version(m) >= 0
header_encoding_offset(::SparseVectorMessage) = 0
header(m::SparseVectorMessage) = SpidersMessageHeader(m.buffer, m.offset + 0)

function format_meta_attribute(::SparseVectorMessage, meta_attribute)
    meta_attribute === :presence && return Symbol("required")
    error(lazy"unknown attribute: $meta_attribute")
end
format_id(::SparseVectorMessage) = 2
format_since_version(::SparseVectorMessage) = 0
format_in_acting_version(m::SparseVectorMessage) = sbe_acting_version(m) >= 0
format_encoding_offset(::SparseVectorMessage) = 64
format_encoding_length(::SparseVectorMessage) = 1
@inline function format(::Type{Integer}, m::SparseVectorMessageDecoder)
    return decode_le(Int8, m.buffer, m.offset + 64)
end
@inline function format(m::SparseVectorMessageDecoder)
    return Format.SbeEnum(decode_le(Int8, m.buffer, m.offset + 64))
end
@inline format!(m::SparseVectorMessageEncoder, value::Format.SbeEnum) = encode_le(Int8, m.buffer, m.offset + 64, Int8(value))

function indiciesFormat_meta_attribute(::SparseVectorMessage, meta_attribute)
    meta_attribute === :presence && return Symbol("required")
    error(lazy"unknown attribute: $meta_attribute")
end
indiciesFormat_id(::SparseVectorMessage) = 3
indiciesFormat_since_version(::SparseVectorMessage) = 0
indiciesFormat_in_acting_version(m::SparseVectorMessage) = sbe_acting_version(m) >= 0
indiciesFormat_encoding_offset(::SparseVectorMessage) = 65
indiciesFormat_encoding_length(::SparseVectorMessage) = 1
@inline function indiciesFormat(::Type{Integer}, m::SparseVectorMessageDecoder)
    return decode_le(Int8, m.buffer, m.offset + 65)
end
@inline function indiciesFormat(m::SparseVectorMessageDecoder)
    return Format.SbeEnum(decode_le(Int8, m.buffer, m.offset + 65))
end
@inline indiciesFormat!(m::SparseVectorMessageEncoder, value::Format.SbeEnum) = encode_le(Int8, m.buffer, m.offset + 65, Int8(value))

function indexing_meta_attribute(::SparseVectorMessage, meta_attribute)
    meta_attribute === :presence && return Symbol("required")
    error(lazy"unknown attribute: $meta_attribute")
end
indexing_id(::SparseVectorMessage) = 4
indexing_since_version(::SparseVectorMessage) = 0
indexing_in_acting_version(m::SparseVectorMessage) = sbe_acting_version(m) >= 0
indexing_encoding_offset(::SparseVectorMessage) = 66
indexing_encoding_length(::SparseVectorMessage) = 1
@inline function indexing(::Type{Integer}, m::SparseVectorMessageDecoder)
    return decode_le(Int8, m.buffer, m.offset + 66)
end
@inline function indexing(m::SparseVectorMessageDecoder)
    return Indexing.SbeEnum(decode_le(Int8, m.buffer, m.offset + 66))
end
@inline indexing!(m::SparseVectorMessageEncoder, value::Indexing.SbeEnum) = encode_le(Int8, m.buffer, m.offset + 66, Int8(value))

function reserved1_meta_attribute(::SparseVectorMessage, meta_attribute)
    meta_attribute === :presence && return Symbol("required")
    error(lazy"unknown attribute: $meta_attribute")
end
reserved1_id(::SparseVectorMessage) = 5
reserved1_since_version(::SparseVectorMessage) = 0
reserved1_in_acting_version(m::SparseVectorMessage) = sbe_acting_version(m) >= 0
reserved1_encoding_offset(::SparseVectorMessage) = 67
reserved1_null_value(::SparseVectorMessage) = Int8(-128)
reserved1_min_value(::SparseVectorMessage) = Int8(-127)
reserved1_max_value(::SparseVectorMessage) = Int8(127)
reserved1_encoding_length(::SparseVectorMessage) = 1

@inline function reserved1(m::SparseVectorMessageDecoder)
    return decode_le(Int8, m.buffer, m.offset + 67)
end
@inline reserved1!(m::SparseVectorMessageEncoder, value) = encode_le(Int8, m.buffer, m.offset + 67, value)

function length_meta_attribute(::SparseVectorMessage, meta_attribute)
    meta_attribute === :presence && return Symbol("required")
    error(lazy"unknown attribute: $meta_attribute")
end
length_id(::SparseVectorMessage) = 6
length_since_version(::SparseVectorMessage) = 0
length_in_acting_version(m::SparseVectorMessage) = sbe_acting_version(m) >= 0
length_encoding_offset(::SparseVectorMessage) = 68
length_null_value(::SparseVectorMessage) = Int64(-9223372036854775808)
length_min_value(::SparseVectorMessage) = Int64(-9223372036854775807)
length_max_value(::SparseVectorMessage) = Int64(9223372036854775807)
length_encoding_length(::SparseVectorMessage) = 8

@inline function length(m::SparseVectorMessageDecoder)
    return decode_le(Int64, m.buffer, m.offset + 68)
end
@inline length!(m::SparseVectorMessageEncoder, value) = encode_le(Int64, m.buffer, m.offset + 68, value)

function indicies_meta_attribute(::SparseVectorMessage, meta_attribute)
    meta_attribute === :semantic_type && return Symbol("int64")
    meta_attribute === :presence && return Symbol("required")
    error(lazy"unknown attribute: $meta_attribute")
end

indicies_character_encoding(::SparseVectorMessage) = "null"
indicies_in_acting_version(m::SparseVectorMessage) = sbe_acting_version(m) >= 0
indicies_id(::SparseVectorMessage) = 20
indicies_header_length(::SparseVectorMessage) = 4

@inline function indicies_length(m::SparseVectorMessage)
    return decode_le(UInt32, m.buffer, sbe_position(m))
end

@inline function indicies_length!(m::SparseVectorMessageEncoder, n)
    if !checkbounds(Bool, m.buffer, sbe_position(m) + 1 + 4 + n)
        error("buffer too short for data length")
    end
    return encode_le(UInt32, m.buffer, sbe_position(m), n)
end

@inline function skip_indicies!(m::SparseVectorMessage)
    len = indicies_length(m)
    pos = sbe_position(m) + len + 4
    sbe_position!(m, pos)
    return len
end

@inline function indicies(m::SparseVectorMessageDecoder)
    len = indicies_length(m)
    pos = sbe_position(m) + 4
    sbe_position!(m, pos + len)
    return view(m.buffer, pos+1:pos+len)
end

@inline function indicies!(m::SparseVectorMessageEncoder, len::Int)
    indicies_length!(m, len)
    pos = sbe_position(m) + 4
    sbe_position!(m, pos + len)
    return view(m.buffer, pos+1:pos+len)
end

@inline function indicies!(m::SparseVectorMessageEncoder, src)
    len = Base.length(src)
    indicies_length!(m, len)
    pos = sbe_position(m) + 4
    sbe_position!(m, pos + len)
    dest = view(m.buffer, pos+1:pos+len)
    copyto!(dest, src)
end

function values_meta_attribute(::SparseVectorMessage, meta_attribute)
    meta_attribute === :presence && return Symbol("required")
    error(lazy"unknown attribute: $meta_attribute")
end

values_character_encoding(::SparseVectorMessage) = "null"
values_in_acting_version(m::SparseVectorMessage) = sbe_acting_version(m) >= 0
values_id(::SparseVectorMessage) = 30
values_header_length(::SparseVectorMessage) = 4

@inline function values_length(m::SparseVectorMessage)
    return decode_le(UInt32, m.buffer, sbe_position(m))
end

@inline function values_length!(m::SparseVectorMessageEncoder, n)
    if !checkbounds(Bool, m.buffer, sbe_position(m) + 1 + 4 + n)
        error("buffer too short for data length")
    end
    return encode_le(UInt32, m.buffer, sbe_position(m), n)
end

@inline function skip_values!(m::SparseVectorMessage)
    len = values_length(m)
    pos = sbe_position(m) + len + 4
    sbe_position!(m, pos)
    return len
end

@inline function values(m::SparseVectorMessageDecoder)
    len = values_length(m)
    pos = sbe_position(m) + 4
    sbe_position!(m, pos + len)
    return view(m.buffer, pos+1:pos+len)
end

@inline function values!(m::SparseVectorMessageEncoder, len::Int)
    values_length!(m, len)
    pos = sbe_position(m) + 4
    sbe_position!(m, pos + len)
    return view(m.buffer, pos+1:pos+len)
end

@inline function values!(m::SparseVectorMessageEncoder, src)
    len = Base.length(src)
    values_length!(m, len)
    pos = sbe_position(m) + 4
    sbe_position!(m, pos + len)
    dest = view(m.buffer, pos+1:pos+len)
    copyto!(dest, src)
end

function Base.show(io::IO, m::SparseVectorMessage{T}) where {T}
    println(io, "SparseVectorMessage view over a type $T")
    println(io, "SbeBlockLength: ", sbe_block_length(m))
    println(io, "SbeTemplateId:  ", sbe_template_id(m))
    println(io, "SbeSchemaId:    ", sbe_schema_id(m))
    println(io, "SbeSchemaVersion: ", sbe_schema_version(m))

    writer = SparseVectorMessageDecoder(sbe_buffer(m), sbe_offset(m), sbe_block_length(m), sbe_schema_version(m))
    print(io, "header: ")
    Base.show(io, header(writer))

    println(io)
    print(io, "format: ")
    print(io, format(writer))

    println(io)
    print(io, "indiciesFormat: ")
    print(io, indiciesFormat(writer))

    println(io)
    print(io, "indexing: ")
    print(io, indexing(writer))

    println(io)
    print(io, "reserved1: ")
    print(io, reserved1(writer))

    println(io)
    print(io, "length: ")
    print(io, length(writer))

    println(io)
    print(io, "indicies: ")
    print(io, skip_indicies!(writer))
    print(io, " bytes of raw data")

    println(io)
    print(io, "values: ")
    print(io, skip_values!(writer))
    print(io, " bytes of raw data")

    nothing
end

@inline function skip!(m::SparseVectorMessage)
    skip_indicies!(m)
    skip_values!(m)
    return
end
