# Generated SBE (Simple Binary Encoding) message codec
# Code generated by SBE. DO NOT EDIT.

struct SparseVectorMessage{T<:AbstractArray{UInt8}}
    buffer::T
    offset::Int64
    position_ptr::Base.RefValue{Int64}
    acting_block_length::Int64
    acting_version::Int64
end

@inline function SparseVectorMessage(context::SbeCodecContext, buffer, offset, acting_block_length, acting_version)
    sbe_position!(context, offset + acting_block_length)
    return SparseVectorMessage(buffer, offset, sbe_position_ptr(context), acting_block_length, acting_version)
end
@inline SparseVectorMessage() = SparseVectorMessage(SbeCodecContext(), UInt8[], 0, 0, 0)

@inline function SparseVectorMessageDecoder(context::SbeCodecContext, buffer, offset,
    acting_block_length, acting_version)
    return SparseVectorMessage(context, buffer, offset, acting_block_length, acting_version)
end

@inline function SparseVectorMessageDecoder(context::SbeCodecContext, buffer, offset, hdr::MessageHeader)
    return SparseVectorMessageDecoder(context, buffer, offset + sbe_encoded_length(hdr),
        Int64(blockLength(hdr)), Int64(version(hdr)))
end

@inline function SparseVectorMessageDecoder(context::SbeCodecContext, buffer, hdr::MessageHeader)
    return SparseVectorMessageDecoder(context, buffer, 0, hdr)
end

@inline function SparseVectorMessageEncoder(context::SbeCodecContext, buffer, offset=0)
    return SparseVectorMessage(context, buffer, offset, 76, 0)
end

@inline function SparseVectorMessageEncoder(context::SbeCodecContext, buffer, offset, hdr::MessageHeader)
    blockLength!(hdr, 76)
    templateId!(hdr, 3)
    schemaId!(hdr, 1)
    version!(hdr, 0)
    return SparseVectorMessage(context, buffer, offset + sbe_encoded_length(hdr), 76, 0)
end

@inline function SparseVectorMessageEncoder(context::SbeCodecContext, buffer, hdr::MessageHeader)
    return SparseVectorMessageEncoder(context, buffer, 0, hdr)
end

sbe_buffer(m::SparseVectorMessage) = @inbounds view(m.buffer, m.offset+1:m.offset+sbe_decoded_length(m))
sbe_offset(m::SparseVectorMessage) = m.offset
sbe_position_ptr(m::SparseVectorMessage) = m.position_ptr
sbe_acting_block_length(m::SparseVectorMessage) = m.acting_block_length
sbe_acting_version(m::SparseVectorMessage) = m.acting_version
sbe_position(m::SparseVectorMessage) = m.position_ptr[]
@inline sbe_check_position(m::SparseVectorMessage, position) = (checkbounds(m.buffer, position + 1); position)
@inline sbe_position!(m::SparseVectorMessage, position) = m.position_ptr[] = sbe_check_position(m, position)
sbe_block_length(::SparseVectorMessage) = 76
sbe_template_id(::SparseVectorMessage) = 3
sbe_schema_id(::SparseVectorMessage) = 1
sbe_schema_version(::SparseVectorMessage) = 0
sbe_semantic_type(::SparseVectorMessage) = ""
sbe_semantic_version(::SparseVectorMessage) = ""
sbe_rewind!(m::SparseVectorMessage) = (sbe_position!(m, m.offset + m.acting_block_length); m)
sbe_encoded_length(m::SparseVectorMessage) = sbe_position(m) - m.offset
@inline function sbe_decoded_length(m::SparseVectorMessage)
    skipper = SparseVectorMessage(SbeCodecContext(), m.buffer, m.offset, 76, sbe_acting_version(m))
    skip!(skipper)
    return sbe_encoded_length(skipper)
end

function header_meta_attribute(::SparseVectorMessage, meta_attribute)
    meta_attribute === :presence && return Symbol("required")
    error(lazy"unknown attribute: $meta_attribute")
end
header_id(::SparseVectorMessage) = 1
header_in_acting_version(m::SparseVectorMessage) = sbe_acting_version(m) >= 0
header_encoding_offset(::SparseVectorMessage) = 0
header(m::SparseVectorMessage) = SpidersMessageHeader(m.buffer, m.offset + 0)

function format_meta_attribute(::SparseVectorMessage, meta_attribute)
    meta_attribute === :presence && return Symbol("required")
    error(lazy"unknown attribute: $meta_attribute")
end
format_id(::SparseVectorMessage) = 2
format_in_acting_version(m::SparseVectorMessage) = sbe_acting_version(m) >= 0
format_encoding_offset(::SparseVectorMessage) = 64
format_encoding_length(::SparseVectorMessage) = 1
@inline function format_raw(m::SparseVectorMessage)
    return decode_le(Int8, m.buffer, m.offset + 64)
end
@inline function format(m::SparseVectorMessage)
    return Format.SbeEnum(decode_le(Int8, m.buffer, m.offset + 64))
end
@inline format!(m::SparseVectorMessage, value::Format.SbeEnum) = encode_le(Int8, m.buffer, m.offset + 64, Int8(value))

function indiciesFormat_meta_attribute(::SparseVectorMessage, meta_attribute)
    meta_attribute === :presence && return Symbol("required")
    error(lazy"unknown attribute: $meta_attribute")
end
indiciesFormat_id(::SparseVectorMessage) = 3
indiciesFormat_in_acting_version(m::SparseVectorMessage) = sbe_acting_version(m) >= 0
indiciesFormat_encoding_offset(::SparseVectorMessage) = 65
indiciesFormat_encoding_length(::SparseVectorMessage) = 1
@inline function indiciesFormat_raw(m::SparseVectorMessage)
    return decode_le(Int8, m.buffer, m.offset + 65)
end
@inline function indiciesFormat(m::SparseVectorMessage)
    return Format.SbeEnum(decode_le(Int8, m.buffer, m.offset + 65))
end
@inline indiciesFormat!(m::SparseVectorMessage, value::Format.SbeEnum) = encode_le(Int8, m.buffer, m.offset + 65, Int8(value))

function indexing_meta_attribute(::SparseVectorMessage, meta_attribute)
    meta_attribute === :presence && return Symbol("required")
    error(lazy"unknown attribute: $meta_attribute")
end
indexing_id(::SparseVectorMessage) = 4
indexing_in_acting_version(m::SparseVectorMessage) = sbe_acting_version(m) >= 0
indexing_encoding_offset(::SparseVectorMessage) = 66
indexing_encoding_length(::SparseVectorMessage) = 1
@inline function indexing_raw(m::SparseVectorMessage)
    return decode_le(Int8, m.buffer, m.offset + 66)
end
@inline function indexing(m::SparseVectorMessage)
    return Indexing.SbeEnum(decode_le(Int8, m.buffer, m.offset + 66))
end
@inline indexing!(m::SparseVectorMessage, value::Indexing.SbeEnum) = encode_le(Int8, m.buffer, m.offset + 66, Int8(value))

function reserved1_meta_attribute(::SparseVectorMessage, meta_attribute)
    meta_attribute === :presence && return Symbol("required")
    error(lazy"unknown attribute: $meta_attribute")
end
reserved1_id(::SparseVectorMessage) = 5
reserved1_in_acting_version(m::SparseVectorMessage) = sbe_acting_version(m) >= 0
reserved1_encoding_offset(::SparseVectorMessage) = 67
reserved1_null_value(::SparseVectorMessage) = Int8(-128)
reserved1_min_value(::SparseVectorMessage) = Int8(-127)
reserved1_max_value(::SparseVectorMessage) = Int8(127)
reserved1_encoding_length(::SparseVectorMessage) = 1

@inline function reserved1(m::SparseVectorMessage)
    return decode_le(Int8, m.buffer, m.offset + 67)
end
@inline reserved1!(m::SparseVectorMessage, value) = encode_le(Int8, m.buffer, m.offset + 67, value)

function length_meta_attribute(::SparseVectorMessage, meta_attribute)
    meta_attribute === :presence && return Symbol("required")
    error(lazy"unknown attribute: $meta_attribute")
end
length_id(::SparseVectorMessage) = 6
length_in_acting_version(m::SparseVectorMessage) = sbe_acting_version(m) >= 0
length_encoding_offset(::SparseVectorMessage) = 68
length_null_value(::SparseVectorMessage) = Int64(-9223372036854775808)
length_min_value(::SparseVectorMessage) = Int64(-9223372036854775807)
length_max_value(::SparseVectorMessage) = Int64(9223372036854775807)
length_encoding_length(::SparseVectorMessage) = 8

@inline function length(m::SparseVectorMessage)
    return decode_le(Int64, m.buffer, m.offset + 68)
end
@inline length!(m::SparseVectorMessage, value) = encode_le(Int64, m.buffer, m.offset + 68, value)

function indicies_meta_attribute(::SparseVectorMessage, meta_attribute)
    meta_attribute === :semantic_type && return Symbol("int64")
    meta_attribute === :presence && return Symbol("required")
    error(lazy"unknown attribute: $meta_attribute")
end

indicies_character_encoding(::SparseVectorMessage) = "null"
indicies_in_acting_version(m::SparseVectorMessage) = sbe_acting_version(m) >= 0
indicies_id(::SparseVectorMessage) = 20
indicies_header_length(::SparseVectorMessage) = 4

@inline function indicies_length(m::SparseVectorMessage)
    return decode_le(UInt32, m.buffer, sbe_position(m))
end

@inline function indicies_length!(m::SparseVectorMessage, n)
    if !checkbounds(Bool, m.buffer, sbe_position(m) + 1 + 4 + n)
        error("buffer too short for data length")
    end
    return encode_le(UInt32, m.buffer, sbe_position(m), n)
end

@inline function skip_indicies!(m::SparseVectorMessage)
    len = indicies_length(m)
    pos = sbe_position(m) + len + 4
    sbe_position!(m, pos)
    return len
end

@inline function indicies(m::SparseVectorMessage)
    len = indicies_length(m)
    pos = sbe_position(m) + 4
    sbe_position!(m, pos + len)
    return @inbounds view(m.buffer, pos+1:pos+len)
end

@inline function indicies!(m::SparseVectorMessage, len::Int)
    indicies_length!(m, len)
    pos = sbe_position(m) + 4
    sbe_position!(m, pos + len)
    return @inbounds view(m.buffer, pos+1:pos+len)
end

function values_meta_attribute(::SparseVectorMessage, meta_attribute)
    meta_attribute === :presence && return Symbol("required")
    error(lazy"unknown attribute: $meta_attribute")
end

values_character_encoding(::SparseVectorMessage) = "null"
values_in_acting_version(m::SparseVectorMessage) = sbe_acting_version(m) >= 0
values_id(::SparseVectorMessage) = 30
values_header_length(::SparseVectorMessage) = 4

@inline function values_length(m::SparseVectorMessage)
    return decode_le(UInt32, m.buffer, sbe_position(m))
end

@inline function values_length!(m::SparseVectorMessage, n)
    if !checkbounds(Bool, m.buffer, sbe_position(m) + 1 + 4 + n)
        error("buffer too short for data length")
    end
    return encode_le(UInt32, m.buffer, sbe_position(m), n)
end

@inline function skip_values!(m::SparseVectorMessage)
    len = values_length(m)
    pos = sbe_position(m) + len + 4
    sbe_position!(m, pos)
    return len
end

@inline function values(m::SparseVectorMessage)
    len = values_length(m)
    pos = sbe_position(m) + 4
    sbe_position!(m, pos + len)
    return @inbounds view(m.buffer, pos+1:pos+len)
end

@inline function values!(m::SparseVectorMessage, len::Int)
    values_length!(m, len)
    pos = sbe_position(m) + 4
    sbe_position!(m, pos + len)
    return @inbounds view(m.buffer, pos+1:pos+len)
end

function print_fields(io::IO, writer::SparseVectorMessage{T}) where {T}
    println(io, "SparseVectorMessage view over a type $T")
    println(io, "SbeBlockLength: ", sbe_block_length(writer))
    println(io, "SbeTemplateId:  ", sbe_template_id(writer))
    println(io, "SbeSchemaId:    ", sbe_schema_id(writer))
    println(io, "SbeSchemaVersion: ", sbe_schema_version(writer))

    sbe_rewind!(writer)
    print(io, "header: ")
    print_fields(io, header(writer))

    println(io)
    print(io, "format: ")
    print(io, format(writer))

    println(io)
    print(io, "indiciesFormat: ")
    print(io, indiciesFormat(writer))

    println(io)
    print(io, "indexing: ")
    print(io, indexing(writer))

    println(io)
    print(io, "reserved1: ")
    print(io, reserved1(writer))

    println(io)
    print(io, "length: ")
    print(io, length(writer))

    println(io)
    print(io, "indicies: ")
    print(io, skip_indicies!(writer))
    print(io, " bytes of raw data")

    println(io)
    print(io, "values: ")
    print(io, skip_values!(writer))
    print(io, " bytes of raw data")

    sbe_rewind!(writer)
    nothing
end

@inline function skip!(m::SparseVectorMessage)
    skip_indicies!(m)
    skip_values!(m)
    return
end
