# Generated SBE (Simple Binary Encoding) message codec
# Code generated by SBE. DO NOT EDIT.

abstract type EventMessage{T} end

struct EventMessageDecoder{T<:AbstractArray{UInt8}} <: EventMessage{T}
    buffer::T
    offset::Int64
    position_ptr::Base.RefValue{Int64}
    acting_block_length::Int64
    acting_version::Int64
end

struct EventMessageEncoder{T<:AbstractArray{UInt8}} <: EventMessage{T}
    buffer::T
    offset::Int64
    position_ptr::Base.RefValue{Int64}
end

@inline function EventMessageDecoder(context::SbeCodecContext, buffer, offset,
    acting_block_length, acting_version)
    sbe_position!(context, offset + acting_block_length)
    EventMessageDecoder(buffer, offset, sbe_position_ptr(context), acting_block_length, acting_version)
end

@inline function EventMessageDecoder(context::SbeCodecContext, buffer, offset, hdr::MessageHeader)
    EventMessageDecoder(context, buffer, offset + sbe_encoded_length(hdr),
        Int64(blockLength(hdr)), Int64(version(hdr)))
end

@inline function EventMessageDecoder(context::SbeCodecContext, buffer, hdr::MessageHeader)
    EventMessageDecoder(context, buffer, 0, hdr)
end
@inline function EventMessageDecoder(buffer, offset, acting_block_length, acting_version)
    EventMessageDecoder(SbeCodecContext(), buffer, offset, acting_block_length, acting_version)
end

@inline EventMessageDecoder(buffer, offset, hdr) = EventMessageDecoder(SbeCodecContext(), buffer, offset, hdr)
@inline EventMessageDecoder(buffer, hdr) = EventMessageDecoder(SbeCodecContext(), buffer, 0, hdr)
 @inline function EventMessageEncoder(context::SbeCodecContext, buffer, offset=0)
    sbe_position!(context, offset + 100)
    EventMessageEncoder(buffer, offset, sbe_position_ptr(context))
end
@inline EventMessageEncoder(buffer, offset=0) = EventMessageEncoder(SbeCodecContext(), buffer, offset)
@inline EventMessage() = EventMessageEncoder(SbeCodecContext(), UInt8[])

@inline function EventMessageEncoder(context::SbeCodecContext, buffer, offset, hdr::MessageHeader)
    blockLength!(hdr, 100)
    templateId!(hdr, 1)
    schemaId!(hdr, 6)
    version!(hdr, 0)
    EventMessageEncoder(context, buffer, offset + sbe_encoded_length(hdr))
end

@inline function EventMessageEncoder(context::SbeCodecContext, buffer, hdr::MessageHeader)
    EventMessageEncoder(context, buffer, 0, hdr)
end

@inline function EventMessageEncoder(buffer, offset, hdr::MessageHeader)
    EventMessageEncoder(SbeCodecContext(), buffer, offset, hdr)
end

@inline function EventMessageEncoder(buffer, hdr::MessageHeader)
    EventMessageEncoder(SbeCodecContext(), buffer, 0, hdr)
end

sbe_buffer(m::EventMessage) = m.buffer
sbe_offset(m::EventMessage) = m.offset
sbe_position_ptr(m::EventMessage) = m.position_ptr
sbe_position(m::EventMessage) = m.position_ptr[]
@inline sbe_check_position(m::EventMessage, position) = (checkbounds(m.buffer, position + 1); position)
@inline sbe_position!(m::EventMessage, position) = m.position_ptr[] = position
sbe_block_length(::EventMessage) = 100
sbe_template_id(::EventMessage) = 1
sbe_schema_id(::EventMessage) = 6
sbe_schema_version(::EventMessage) = 0
sbe_semantic_type(::EventMessage) = ""
sbe_semantic_version(::EventMessage) = ""
sbe_encoded_length(m::EventMessageEncoder) = sbe_position(m) - m.offset
sbe_rewind!(m::EventMessageEncoder) = sbe_position!(m, m.offset + 100)

sbe_acting_block_length(m::EventMessageDecoder) = m.acting_block_length
sbe_acting_version(m::EventMessageDecoder) = m.acting_version
sbe_rewind!(m::EventMessageDecoder) = sbe_position!(m, m.offset + m.acting_block_length)

@inline function sbe_decoded_length(m::EventMessageDecoder)
    skipper = EventMessageEncoder(m.buffer, m.offset)
    skip!(skipper)
    return sbe_encoded_length(skipper)
end

function sbe_decoded_buffer(m::EventMessageDecoder)
    offset = m.offset - sbe_encoded_length(MessageHeader())
    offset < 0 && throw(ArgumentError("Message offset is negative"))
    return view(m.buffer, offset+1:offset+sbe_decoded_length(m))
end

function sbe_encoded_buffer(m::EventMessageEncoder)
    offset = m.offset - sbe_encoded_length(MessageHeader())
    offset < 0 && throw(ArgumentError("Message offset is negative"))
    d = EventMessageDecoder(m.buffer, MessageHeader(m.buffer, offset))
    return view(d.buffer, offset+1:offset+sbe_decoded_length(d))
end

function header_meta_attribute(::EventMessage, meta_attribute)
    meta_attribute === :presence && return Symbol("required")
    error(lazy"unknown attribute: $meta_attribute")
end
header_id(::EventMessage) = 1
header_since_version(::EventMessage) = 0
header_in_acting_version(m::EventMessage) = sbe_acting_version(m) >= 0
header_encoding_offset(::EventMessage) = 0
header(m::EventMessage) = SpidersMessageHeader(m.buffer, m.offset + 0)

function format_meta_attribute(::EventMessage, meta_attribute)
    meta_attribute === :presence && return Symbol("required")
    error(lazy"unknown attribute: $meta_attribute")
end
format_id(::EventMessage) = 2
format_since_version(::EventMessage) = 0
format_in_acting_version(m::EventMessage) = sbe_acting_version(m) >= 0
format_encoding_offset(::EventMessage) = 64
format_encoding_length(::EventMessage) = 1
@inline function format(::Type{Integer}, m::EventMessageDecoder)
    return decode_le(Int8, m.buffer, m.offset + 64)
end
@inline function format(m::EventMessageDecoder)
    return Format.SbeEnum(decode_le(Int8, m.buffer, m.offset + 64))
end
@inline format!(m::EventMessageEncoder, value::Format.SbeEnum) = encode_le(Int8, m.buffer, m.offset + 64, Int8(value))

function reserved1_meta_attribute(::EventMessage, meta_attribute)
    meta_attribute === :presence && return Symbol("required")
    error(lazy"unknown attribute: $meta_attribute")
end
reserved1_id(::EventMessage) = 9
reserved1_since_version(::EventMessage) = 0
reserved1_in_acting_version(m::EventMessage) = sbe_acting_version(m) >= 0
reserved1_encoding_offset(::EventMessage) = 65
reserved1_null_value(::EventMessage) = Int8(-128)
reserved1_min_value(::EventMessage) = Int8(-127)
reserved1_max_value(::EventMessage) = Int8(127)
reserved1_encoding_length(::EventMessage) = 3
reserved1_length(::EventMessage) = 3
reserved1_eltype(::EventMessage) = Int8

@inline function reserved1(m::EventMessageDecoder)
    return mappedarray(ltoh, reinterpret(Int8, view(m.buffer, m.offset+65+1:m.offset+65+sizeof(Int8)*3)))
end

@inline function reserved1(::Type{<:SVector},m::EventMessageDecoder)
    return mappedarray(ltoh, reinterpret(SVector{3,Int8}, view(m.buffer, m.offset+65+1:m.offset+65+sizeof(Int8)*3))[])
end

@inline function reserved1!(m::EventMessageEncoder)
    return mappedarray(ltoh, htol, reinterpret(Int8, view(m.buffer, m.offset+65+1:m.offset+65+sizeof(Int8)*3)))
end

@inline function reserved1!(m::EventMessageEncoder, value)
    copyto!(mappedarray(ltoh, htol, reinterpret(Int8, view(m.buffer, m.offset+65+1:m.offset+65+sizeof(Int8)*3))), value)
end

function key_meta_attribute(::EventMessage, meta_attribute)
    meta_attribute === :presence && return Symbol("required")
    error(lazy"unknown attribute: $meta_attribute")
end
key_id(::EventMessage) = 10
key_since_version(::EventMessage) = 0
key_in_acting_version(m::EventMessage) = sbe_acting_version(m) >= 0
key_encoding_offset(::EventMessage) = 68
key_null_value(::EventMessage) = UInt8(0x0)
key_min_value(::EventMessage) = UInt8(0x20)
key_max_value(::EventMessage) = UInt8(0x7e)
key_encoding_length(::EventMessage) = 32
key_length(::EventMessage) = 32
key_eltype(::EventMessage) = UInt8

@inline function key(m::EventMessageDecoder)
    return mappedarray(ltoh, reinterpret(UInt8, view(m.buffer, m.offset+68+1:m.offset+68+sizeof(UInt8)*32)))
end

@inline function key(::Type{<:SVector},m::EventMessageDecoder)
    return mappedarray(ltoh, reinterpret(SVector{32,UInt8}, view(m.buffer, m.offset+68+1:m.offset+68+sizeof(UInt8)*32))[])
end

@inline function key(::Type{<:AbstractString}, m::EventMessageDecoder)
    value = view(m.buffer, m.offset+1+68:m.offset+68+sizeof(UInt8)*32)
    return StringView(rstrip_nul(value))
end

@inline function key!(m::EventMessageEncoder)
    return mappedarray(ltoh, htol, reinterpret(UInt8, view(m.buffer, m.offset+68+1:m.offset+68+sizeof(UInt8)*32)))
end

@inline function key!(m::EventMessageEncoder, value)
    copyto!(mappedarray(ltoh, htol, reinterpret(UInt8, view(m.buffer, m.offset+68+1:m.offset+68+sizeof(UInt8)*32))), value)
end

function value_meta_attribute(::EventMessage, meta_attribute)
    meta_attribute === :presence && return Symbol("required")
    error(lazy"unknown attribute: $meta_attribute")
end

value_character_encoding(::EventMessage) = "null"
value_in_acting_version(m::EventMessage) = sbe_acting_version(m) >= 0
value_id(::EventMessage) = 20
value_header_length(::EventMessage) = 4

@inline function value_length(m::EventMessage)
    return decode_le(UInt32, m.buffer, sbe_position(m))
end

@inline function value_length!(m::EventMessageEncoder, n)
    if !checkbounds(Bool, m.buffer, sbe_position(m) + 1 + 4 + n)
        error("buffer too short for data length")
    end
    return encode_le(UInt32, m.buffer, sbe_position(m), n)
end

@inline function skip_value!(m::EventMessage)
    len = value_length(m)
    pos = sbe_position(m) + len + 4
    sbe_position!(m, pos)
    return len
end

@inline function value(m::EventMessageDecoder)
    len = value_length(m)
    pos = sbe_position(m) + 4
    sbe_position!(m, pos + len)
    return view(m.buffer, pos+1:pos+len)
end

@inline function value!(m::EventMessageEncoder, len::Int)
    value_length!(m, len)
    pos = sbe_position(m) + 4
    sbe_position!(m, pos + len)
    return view(m.buffer, pos+1:pos+len)
end

@inline function value!(m::EventMessageEncoder, src)
    len = Base.length(src)
    value_length!(m, len)
    pos = sbe_position(m) + 4
    sbe_position!(m, pos + len)
    dest = view(m.buffer, pos+1:pos+len)
    copyto!(dest, src)
end

function Base.show(io::IO, m::EventMessage{T}) where {T}
    println(io, "EventMessage view over a type $T")
    println(io, "SbeBlockLength: ", sbe_block_length(m))
    println(io, "SbeTemplateId:  ", sbe_template_id(m))
    println(io, "SbeSchemaId:    ", sbe_schema_id(m))
    println(io, "SbeSchemaVersion: ", sbe_schema_version(m))

    writer = EventMessageDecoder(sbe_buffer(m), sbe_offset(m), sbe_block_length(m), sbe_schema_version(m))
    print(io, "header: ")
    Base.show(io, header(writer))

    println(io)
    print(io, "format: ")
    print(io, format(writer))

    println(io)
    print(io, "reserved1: ")
    print(io, reserved1(writer))

    println(io)
    print(io, "key: ")
    print(io, "\"")
    print(io, key(StringView, writer))
    print(io, "\"")

    println(io)
    print(io, "value: ")
    print(io, skip_value!(writer))
    print(io, " bytes of raw data")

    nothing
end

@inline function skip!(m::EventMessage)
    skip_value!(m)
    return
end
