# Generated SBE (Simple Binary Encoding) message codec
# Code generated by SBE. DO NOT EDIT.

module Event

using EnumX
using MappedArrays
using StaticArrays
using StringViews

include("Utils.jl")
include("Format.jl")
include("SpidersMessageHeader.jl")
include("MessageHeader.jl")
include("VarDataEncoding.jl")
include("EventMessage.jl")
end
