# Generated SBE (Simple Binary Encoding) message codec
# Code generated by SBE. DO NOT EDIT.

export ChunkDataMessage, ChunkDataMessageDecoder, ChunkDataMessageEncoder
abstract type ChunkDataMessage{T} end

struct ChunkDataMessageDecoder{T<:AbstractArray{UInt8}} <: ChunkDataMessage{T}
    buffer::T
    offset::Int64
    position_ptr::Base.RefValue{Int64}
    acting_block_length::UInt16
    acting_version::UInt16
    function ChunkDataMessageDecoder(buffer::T, offset::Integer, position_ptr::Ref{Int64},
        acting_block_length::Integer, acting_version::Integer) where {T}
        position_ptr[] = offset + acting_block_length
        new{T}(buffer, offset, position_ptr, acting_block_length, acting_version)
    end
end

struct ChunkDataMessageEncoder{T<:AbstractArray{UInt8}} <: ChunkDataMessage{T}
    buffer::T
    offset::Int64
    position_ptr::Base.RefValue{Int64}
    function ChunkDataMessageEncoder(buffer::T, offset::Integer, position_ptr::Ref{Int64}) where {T}
        position_ptr[] = offset + 72
        new{T}(buffer, offset, position_ptr)
    end
end

@inline function ChunkDataMessageDecoder(buffer::AbstractArray, offset::Integer=0;
    position_ptr::Base.RefValue{Int64}=Ref(0),
    header::MessageHeader=MessageHeader(buffer, offset))
    if templateId(header) != UInt16(0x1f) || schemaId(header) != UInt16(0x1)
        error("Template id or schema id mismatch")
    end
    ChunkDataMessageDecoder(buffer, offset + sbe_encoded_length(header), position_ptr,
        blockLength(header), version(header))
end
@inline function ChunkDataMessageEncoder(buffer::AbstractArray, offset::Integer=0;
    position_ptr::Base.RefValue{Int64}=Ref(0),
    header::MessageHeader=MessageHeader(buffer, offset))
    blockLength!(header, UInt16(0x48))
    templateId!(header, UInt16(0x1f))
    schemaId!(header, UInt16(0x1))
    version!(header, UInt16(0x0))
    ChunkDataMessageEncoder(buffer, offset + sbe_encoded_length(header), position_ptr)
end
sbe_buffer(m::ChunkDataMessage) = m.buffer
sbe_offset(m::ChunkDataMessage) = m.offset
sbe_position_ptr(m::ChunkDataMessage) = m.position_ptr
sbe_position(m::ChunkDataMessage) = m.position_ptr[]
sbe_position!(m::ChunkDataMessage, position) = m.position_ptr[] = position
sbe_block_length(::ChunkDataMessage) = UInt16(0x48)
sbe_block_length(::Type{<:ChunkDataMessage}) = UInt16(0x48)
sbe_template_id(::ChunkDataMessage) = UInt16(0x1f)
sbe_template_id(::Type{<:ChunkDataMessage})  = UInt16(0x1f)
sbe_schema_id(::ChunkDataMessage) = UInt16(0x1)
sbe_schema_id(::Type{<:ChunkDataMessage})  = UInt16(0x1)
sbe_schema_version(::ChunkDataMessage) = UInt16(0x0)
sbe_schema_version(::Type{<:ChunkDataMessage})  = UInt16(0x0)
sbe_semantic_type(::ChunkDataMessage) = ""
sbe_semantic_version(::ChunkDataMessage) = ""
sbe_acting_block_length(m::ChunkDataMessageDecoder) = m.acting_block_length
sbe_acting_block_length(::ChunkDataMessageEncoder) = UInt16(0x48)
sbe_acting_version(m::ChunkDataMessageDecoder) = m.acting_version
sbe_acting_version(::ChunkDataMessageEncoder) = UInt16(0x0)
sbe_rewind!(m::ChunkDataMessage) = sbe_position!(m, m.offset + sbe_acting_block_length(m))
sbe_encoded_length(m::ChunkDataMessage) = sbe_position(m) - m.offset
@inline function sbe_decoded_length(m::ChunkDataMessage)
    skipper = ChunkDataMessageDecoder(sbe_buffer(m), sbe_offset(m), Ref(0),
        sbe_acting_block_length(m), sbe_acting_version(m))
    sbe_skip!(skipper)
    sbe_encoded_length(skipper)
end

function header_meta_attribute(::ChunkDataMessage, meta_attribute)
    meta_attribute === :presence && return Symbol("required")
    return Symbol("")
end
header_id(::ChunkDataMessage) = UInt16(0x1)
header_since_version(::ChunkDataMessage) = UInt16(0x0)
header_in_acting_version(m::ChunkDataMessage) = sbe_acting_version(m) >= UInt16(0x0)
header_encoding_offset(::ChunkDataMessage) = 0
header(m::ChunkDataMessage) = SpidersMessageHeader(m.buffer, m.offset + 0, sbe_acting_version(m))

function offset_meta_attribute(::ChunkDataMessage, meta_attribute)
    meta_attribute === :presence && return Symbol("required")
    return Symbol("")
end
offset_id(::ChunkDataMessage) = UInt16(0x2)
offset_since_version(::ChunkDataMessage) = UInt16(0x0)
offset_in_acting_version(m::ChunkDataMessage) = sbe_acting_version(m) >= UInt16(0x0)
offset_encoding_offset(::ChunkDataMessage) = 64
offset_null_value(::ChunkDataMessage) = Int64(-9223372036854775808)
offset_min_value(::ChunkDataMessage) = Int64(-9223372036854775807)
offset_max_value(::ChunkDataMessage) = Int64(9223372036854775807)
offset_encoding_length(::ChunkDataMessage) = 8

@inline function offset(m::ChunkDataMessageDecoder)
    return decode_le(Int64, m.buffer, m.offset + 64)
end
@inline offset!(m::ChunkDataMessageEncoder, value) = encode_le(Int64, m.buffer, m.offset + 64, value)

function chunk_meta_attribute(::ChunkDataMessage, meta_attribute)
    meta_attribute === :presence && return Symbol("required")
    return Symbol("")
end

chunk_character_encoding(::ChunkDataMessage) = "null"
chunk_in_acting_version(m::ChunkDataMessage) = sbe_acting_version(m) >= 0
chunk_id(::ChunkDataMessage) = 10
chunk_header_length(::ChunkDataMessage) = 4

@inline function chunk_length(m::ChunkDataMessage)
    return decode_le(UInt32, m.buffer, sbe_position(m))
end

@inline function chunk_length!(m::ChunkDataMessageEncoder, n)
    if !checkbounds(Bool, m.buffer, sbe_position(m) + 4 + n)
        error("buffer too short for data length")
    elseif n > 1073741824
        error("data length too large for length type")
    end
    return encode_le(UInt32, m.buffer, sbe_position(m), n)
end

@inline function skip_chunk!(m::ChunkDataMessage)
    len = chunk_length(m)
    pos = sbe_position(m) + 4
    sbe_position!(m, pos + len)
    return len
end

@inline function chunk(m::ChunkDataMessageDecoder)
    len = chunk_length(m)
    pos = sbe_position(m) + 4
    sbe_position!(m, pos + len)
    return view(m.buffer, pos+1:pos+len)
end

@inline function chunk!(m::ChunkDataMessageEncoder; length::Int64)
    chunk_length!(m, length)
    pos = sbe_position(m) + 4
    sbe_position!(m, pos + length)
    return view(m.buffer, pos+1:pos+length)
end

@inline function chunk!(m::ChunkDataMessageEncoder, src)
    len = Base.length(src)
    chunk_length!(m, len)
    pos = sbe_position(m) + 4
    sbe_position!(m, pos + len)
    dest = view(m.buffer, pos+1:pos+len)
    copyto!(dest, src)
end

function show(io::IO, m::ChunkDataMessage{T}) where {T}
    println(io, "ChunkDataMessage view over a type $T")
    println(io, "SbeBlockLength: ", sbe_block_length(m))
    println(io, "SbeTemplateId:  ", sbe_template_id(m))
    println(io, "SbeSchemaId:    ", sbe_schema_id(m))
    println(io, "SbeSchemaVersion: ", sbe_schema_version(m))

    writer = ChunkDataMessageDecoder(sbe_buffer(m), sbe_offset(m), Ref(0),
        sbe_block_length(m), sbe_schema_version(m))
    print(io, "header: ")
    show(io, header(writer))

    println(io)
    print(io, "offset: ")
    print(io, offset(writer))

    println(io)
    print(io, "chunk: ")
    print(io, skip_chunk!(writer))
    print(io, " bytes of raw data")

    nothing
end

@inline function sbe_skip!(m::ChunkDataMessage)
    sbe_rewind!(m)
    skip_chunk!(m)
    return
end
