# Generated SBE (Simple Binary Encoding) message codec
# Code generated by SBE. DO NOT EDIT.

export ChunkHeaderMessage, ChunkHeaderMessageDecoder, ChunkHeaderMessageEncoder
abstract type ChunkHeaderMessage{T} end

struct ChunkHeaderMessageDecoder{T<:AbstractArray{UInt8}} <: ChunkHeaderMessage{T}
    buffer::T
    offset::Int64
    position_ptr::Base.RefValue{Int64}
    acting_block_length::UInt16
    acting_version::UInt16
    function ChunkHeaderMessageDecoder(buffer::T, offset::Integer, position_ptr::Ref{Int64},
        acting_block_length::Integer, acting_version::Integer) where {T}
        position_ptr[] = offset + acting_block_length
        new{T}(buffer, offset, position_ptr, acting_block_length, acting_version)
    end
end

struct ChunkHeaderMessageEncoder{T<:AbstractArray{UInt8},HasSbeHeader} <: ChunkHeaderMessage{T}
    buffer::T
    offset::Int64
    position_ptr::Base.RefValue{Int64}
    function ChunkHeaderMessageEncoder(buffer::T, offset::Integer,
        position_ptr::Ref{Int64}, hasSbeHeader::Bool=false) where {T}
        position_ptr[] = offset + 80
        new{T,hasSbeHeader}(buffer, offset, position_ptr)
    end
end

@inline function ChunkHeaderMessageDecoder(buffer::AbstractArray, offset::Integer=0;
    position_ptr::Base.RefValue{Int64}=Ref(0),
    header::MessageHeader=MessageHeader(buffer, offset))
    if templateId(header) != UInt16(0x1e) || schemaId(header) != UInt16(0x1)
        throw(DomainError("Template id or schema id mismatch"))
    end
    ChunkHeaderMessageDecoder(buffer, offset + sbe_encoded_length(header), position_ptr,
        blockLength(header), version(header))
end
@inline function ChunkHeaderMessageEncoder(buffer::AbstractArray, offset::Integer=0;
    position_ptr::Base.RefValue{Int64}=Ref(0),
    header::MessageHeader=MessageHeader(buffer, offset))
    blockLength!(header, UInt16(0x50))
    templateId!(header, UInt16(0x1e))
    schemaId!(header, UInt16(0x1))
    version!(header, UInt16(0x0))
    ChunkHeaderMessageEncoder(buffer, offset + sbe_encoded_length(header), position_ptr, true)
end
sbe_buffer(m::ChunkHeaderMessage) = m.buffer
sbe_offset(m::ChunkHeaderMessage) = m.offset
sbe_position_ptr(m::ChunkHeaderMessage) = m.position_ptr
sbe_position(m::ChunkHeaderMessage) = m.position_ptr[]
sbe_position!(m::ChunkHeaderMessage, position) = m.position_ptr[] = position
sbe_block_length(::ChunkHeaderMessage) = UInt16(0x50)
sbe_block_length(::Type{<:ChunkHeaderMessage}) = UInt16(0x50)
sbe_template_id(::ChunkHeaderMessage) = UInt16(0x1e)
sbe_template_id(::Type{<:ChunkHeaderMessage})  = UInt16(0x1e)
sbe_schema_id(::ChunkHeaderMessage) = UInt16(0x1)
sbe_schema_id(::Type{<:ChunkHeaderMessage})  = UInt16(0x1)
sbe_schema_version(::ChunkHeaderMessage) = UInt16(0x0)
sbe_schema_version(::Type{<:ChunkHeaderMessage})  = UInt16(0x0)
sbe_semantic_type(::ChunkHeaderMessage) = ""
sbe_semantic_version(::ChunkHeaderMessage) = ""
sbe_acting_block_length(m::ChunkHeaderMessageDecoder) = m.acting_block_length
sbe_acting_block_length(::ChunkHeaderMessageEncoder) = UInt16(0x50)
sbe_acting_version(m::ChunkHeaderMessageDecoder) = m.acting_version
sbe_acting_version(::ChunkHeaderMessageEncoder) = UInt16(0x0)
sbe_rewind!(m::ChunkHeaderMessage) = sbe_position!(m, m.offset + sbe_acting_block_length(m))
sbe_encoded_length(m::ChunkHeaderMessage) = sbe_position(m) - m.offset
@inline function sbe_decoded_length(m::ChunkHeaderMessage)
    skipper = ChunkHeaderMessageDecoder(sbe_buffer(m), sbe_offset(m), Ref(0),
        sbe_acting_block_length(m), sbe_acting_version(m))
    sbe_skip!(skipper)
    sbe_encoded_length(skipper)
end

Base.sizeof(m::ChunkHeaderMessage) = sbe_decoded_length(m)
function Base.convert(::Type{AbstractArray{UInt8}}, m::ChunkHeaderMessageEncoder{<:AbstractArray{UInt8},true})
    return view(m.buffer, m.offset+1-sbe_encoded_length(MessageHeader):m.offset+sbe_encoded_length(m))
end
function Base.convert(::Type{AbstractArray{UInt8}}, m::ChunkHeaderMessageEncoder{<:AbstractArray{UInt8},false})
    return view(m.buffer, m.offset+1:m.offset+sbe_encoded_length(m))
end

function header_meta_attribute(::ChunkHeaderMessage, meta_attribute)
    meta_attribute === :presence && return Symbol("required")
    return Symbol("")
end
header_id(::ChunkHeaderMessage) = UInt16(0x1)
header_since_version(::ChunkHeaderMessage) = UInt16(0x0)
header_in_acting_version(m::ChunkHeaderMessage) = sbe_acting_version(m) >= UInt16(0x0)
header_encoding_offset(::ChunkHeaderMessage) = 0
header(m::ChunkHeaderMessage) = SpidersMessageHeader(m.buffer, m.offset + 0, sbe_acting_version(m))

function sequencenumber_meta_attribute(::ChunkHeaderMessage, meta_attribute)
    meta_attribute === :presence && return Symbol("required")
    return Symbol("")
end
sequencenumber_id(::ChunkHeaderMessage) = UInt16(0x2)
sequencenumber_since_version(::ChunkHeaderMessage) = UInt16(0x0)
sequencenumber_in_acting_version(m::ChunkHeaderMessage) = sbe_acting_version(m) >= UInt16(0x0)
sequencenumber_encoding_offset(::ChunkHeaderMessage) = 64
sequencenumber_null_value(::ChunkHeaderMessage) = Int64(-9223372036854775808)
sequencenumber_min_value(::ChunkHeaderMessage) = Int64(-9223372036854775807)
sequencenumber_max_value(::ChunkHeaderMessage) = Int64(9223372036854775807)
sequencenumber_encoding_length(::ChunkHeaderMessage) = 8

@inline function sequencenumber(m::ChunkHeaderMessageDecoder)
    return decode_le(Int64, m.buffer, m.offset + 64)
end
@inline sequencenumber!(m::ChunkHeaderMessageEncoder, value) = encode_le(Int64, m.buffer, m.offset + 64, value)

function length_meta_attribute(::ChunkHeaderMessage, meta_attribute)
    meta_attribute === :presence && return Symbol("required")
    return Symbol("")
end
length_id(::ChunkHeaderMessage) = UInt16(0x3)
length_since_version(::ChunkHeaderMessage) = UInt16(0x0)
length_in_acting_version(m::ChunkHeaderMessage) = sbe_acting_version(m) >= UInt16(0x0)
length_encoding_offset(::ChunkHeaderMessage) = 72
length_null_value(::ChunkHeaderMessage) = Int64(-9223372036854775808)
length_min_value(::ChunkHeaderMessage) = Int64(-9223372036854775807)
length_max_value(::ChunkHeaderMessage) = Int64(9223372036854775807)
length_encoding_length(::ChunkHeaderMessage) = 8

@inline function length(m::ChunkHeaderMessageDecoder)
    return decode_le(Int64, m.buffer, m.offset + 72)
end
@inline length!(m::ChunkHeaderMessageEncoder, value) = encode_le(Int64, m.buffer, m.offset + 72, value)

export ChunkHeaderMessageMetadata, ChunkHeaderMessageMetadataDecoder, ChunkHeaderMessageMetadataEncoder
abstract type ChunkHeaderMessageMetadata{T} end

mutable struct ChunkHeaderMessageMetadataDecoder{T<:AbstractArray{UInt8}} <: ChunkHeaderMessageMetadata{T}
    const buffer::T
    offset::Int64
    const position_ptr::Base.RefValue{Int64}
    const block_length::UInt16
    const acting_version::UInt16
    const count::UInt16
    index::UInt16
    function ChunkHeaderMessageMetadataDecoder(buffer::T, offset::Integer, position_ptr::Ref{Int64},
        block_length::Integer, acting_version::Integer,
        count::Integer, index::Integer) where {T}
        new{T}(buffer, offset, position_ptr, block_length, acting_version, count, index)
    end
end

mutable struct ChunkHeaderMessageMetadataEncoder{T<:AbstractArray{UInt8}} <: ChunkHeaderMessageMetadata{T}
    const buffer::T
    offset::Int64
    const position_ptr::Base.RefValue{Int64}
    const initial_position::Int64
    const count::UInt16
    index::UInt16
    function ChunkHeaderMessageMetadataEncoder(buffer::T, offset::Integer, position_ptr::Ref{Int64},
        initial_position::Int64, count::Integer, index::Integer) where {T}
        new{T}(buffer, offset, position_ptr, initial_position, count, index)
    end
end

@inline function ChunkHeaderMessageMetadataDecoder(buffer, position_ptr, acting_version)
    dimensions = GroupSizeEncoding(buffer, position_ptr[])
    position_ptr[] += 4
    return ChunkHeaderMessageMetadataDecoder(buffer, 0, position_ptr, blockLength(dimensions),
        acting_version, numInGroup(dimensions), 0)
end

@inline function ChunkHeaderMessageMetadataEncoder(buffer, count, position_ptr)
    if count > 65534
        error("count outside of allowed range")
    end
    dimensions = GroupSizeEncoding(buffer, position_ptr[])
    blockLength!(dimensions, UInt16(0x1))
    numInGroup!(dimensions, count)
    initial_position = position_ptr[]
    position_ptr[] += 4
    return ChunkHeaderMessageMetadataEncoder(buffer, 0, position_ptr, initial_position, count, 0)
end

sbe_header_size(::ChunkHeaderMessageMetadata) = 4
sbe_block_length(::ChunkHeaderMessageMetadata) = UInt16(0x1)
sbe_acting_block_length(g::ChunkHeaderMessageMetadataDecoder) = g.block_length
sbe_acting_block_length(g::ChunkHeaderMessageMetadataEncoder) = UInt16(0x1)
sbe_acting_version(g::ChunkHeaderMessageMetadataDecoder) = g.acting_version
sbe_acting_version(::ChunkHeaderMessageMetadataEncoder) = UInt16(0x0)
sbe_position(g::ChunkHeaderMessageMetadata) = g.position_ptr[]
@inline sbe_position!(g::ChunkHeaderMessageMetadata, position) = g.position_ptr[] = position
sbe_position_ptr(g::ChunkHeaderMessageMetadata) = g.position_ptr
@inline function next!(g::ChunkHeaderMessageMetadata)
    if g.index >= g.count
        error("index >= count")
    end
    g.offset = sbe_position(g)
    sbe_position!(g, g.offset + sbe_acting_block_length(g))
    g.index += 1
    return g
end
function Base.iterate(g::ChunkHeaderMessageMetadata, state=nothing)
    if g.index < g.count
        g.offset = sbe_position(g)
        sbe_position!(g, g.offset + sbe_acting_block_length(g))
        g.index += 1
        return g, state
    else
        return nothing
    end
end
Base.eltype(::Type{<:ChunkHeaderMessageMetadata}) = ChunkHeaderMessageMetadata
Base.isdone(g::ChunkHeaderMessageMetadata, state=nothing) = g.index >= g.count
Base.length(g::ChunkHeaderMessageMetadata) = g.count

function reset_count_to_index!(g::ChunkHeaderMessageMetadataEncoder)
    g.count = g.index
    dimensions = GroupSizeEncoding(g.buffer, g.initial_position)
    numInGroup!(dimensions, g.count)
    return g.count
end

function format_meta_attribute(::ChunkHeaderMessageMetadata, meta_attribute)
    meta_attribute === :presence && return Symbol("required")
    return Symbol("")
end
format_id(::ChunkHeaderMessageMetadata) = UInt16(0x1)
format_since_version(::ChunkHeaderMessageMetadata) = UInt16(0x0)
format_in_acting_version(m::ChunkHeaderMessageMetadata) = sbe_acting_version(m) >= UInt16(0x0)
format_encoding_offset(::ChunkHeaderMessageMetadata) = 0
format_encoding_length(::ChunkHeaderMessageMetadata) = 1
@inline function format(m::ChunkHeaderMessageMetadataDecoder, ::Type{Integer})
    return decode_le(Int8, m.buffer, m.offset + 0)
end
@inline function format(m::ChunkHeaderMessageMetadataDecoder)
    return Format.SbeEnum(decode_le(Int8, m.buffer, m.offset + 0))
end
@inline format!(m::ChunkHeaderMessageMetadataEncoder, value::Format.SbeEnum) = encode_le(Int8, m.buffer, m.offset + 0, Int8(value))

function key_meta_attribute(::ChunkHeaderMessageMetadata, meta_attribute)
    meta_attribute === :presence && return Symbol("required")
    return Symbol("")
end

key_character_encoding(::ChunkHeaderMessageMetadata) = "UTF-8"
key_in_acting_version(m::ChunkHeaderMessageMetadata) = sbe_acting_version(m) >= 0
key_id(::ChunkHeaderMessageMetadata) = 3
key_header_length(::ChunkHeaderMessageMetadata) = 4

@inline function key_length(m::ChunkHeaderMessageMetadata)
    return decode_le(UInt32, m.buffer, sbe_position(m))
end

@inline function key_length!(m::ChunkHeaderMessageMetadataEncoder, n)
    @boundscheck n > 1073741824 && throw(ArgumentError("length exceeds schema limit"))
    @boundscheck checkbounds(m.buffer, sbe_position(m) + 4 + n)
    return encode_le(UInt32, m.buffer, sbe_position(m), n)
end

@inline function skip_key!(m::ChunkHeaderMessageMetadataDecoder)
    len = key_length(m)
    pos = sbe_position(m) + 4
    sbe_position!(m, pos + len)
    return len
end

@inline function key(m::ChunkHeaderMessageMetadataDecoder)
    len = key_length(m)
    pos = sbe_position(m) + 4
    sbe_position!(m, pos + len)
    return view(m.buffer, pos+1:pos+len)
end

@inline key(m::ChunkHeaderMessageMetadataDecoder, ::Type{AbstractArray{T}}) where {T<:Real} = reinterpret(T, key(m))
@inline key(m::ChunkHeaderMessageMetadataDecoder, ::Type{NTuple{N,T}}) where {N,T<:Real} = (x = reinterpret(T, key(m)); ntuple(i -> x[i], Val(N)))
@inline key(m::ChunkHeaderMessageMetadataDecoder, ::Type{T}) where {T<:AbstractString} = StringView(rstrip_nul(key(m)))
@inline key(m::ChunkHeaderMessageMetadataDecoder, ::Type{T}) where {T<:Symbol} = Symbol(key(m, StringView))
@inline key(m::ChunkHeaderMessageMetadataDecoder, ::Type{T}) where {T<:Real} = reinterpret(T, key(m))[]
@inline key(m::ChunkHeaderMessageMetadataDecoder, ::Type{T}) where {T<:Nothing} = (skip_key!(m); nothing)

@inline function key_buffer!(m::ChunkHeaderMessageMetadataEncoder, len)
    key_length!(m, len)
    pos = sbe_position(m) + 4
    sbe_position!(m, pos + len)
    return view(m.buffer, pos+1:pos+len)
end

@inline function key!(m::ChunkHeaderMessageMetadataEncoder, src::AbstractArray)
    len = sizeof(src)
    key_length!(m, len)
    pos = sbe_position(m) + 4
    sbe_position!(m, pos + len)
    dest = view(m.buffer, pos+1:pos+len)
    copyto!(dest, reinterpret(UInt8, src))
end

@inline function key!(m::ChunkHeaderMessageMetadataEncoder, src::NTuple)
    len = sizeof(src)
    key_length!(m, len)
    pos = sbe_position(m) + 4
    sbe_position!(m, pos + len)
    dest = view(m.buffer, pos+1:pos+len)
    copyto!(dest, reinterpret(NTuple{len,UInt8}, src))
end

@inline function key!(m::ChunkHeaderMessageMetadataEncoder, src::AbstractString)
    len = sizeof(src)
    key_length!(m, len)
    pos = sbe_position(m) + 4
    sbe_position!(m, pos + len)
    dest = view(m.buffer, pos+1:pos+len)
    copyto!(dest, codeunits(src))
end

@inline key!(m::ChunkHeaderMessageMetadataEncoder, src::Symbol) = key!(m, to_string(src))
@inline key!(m::ChunkHeaderMessageMetadataEncoder, src::StaticString) = key!(m, Tuple(src))
@inline key!(m::ChunkHeaderMessageMetadataEncoder, src::Real) = key!(m, Tuple(src))
@inline key!(m::ChunkHeaderMessageMetadataEncoder, ::Nothing) = key_buffer!(m, 0)

function value_meta_attribute(::ChunkHeaderMessageMetadata, meta_attribute)
    meta_attribute === :presence && return Symbol("required")
    return Symbol("")
end

value_character_encoding(::ChunkHeaderMessageMetadata) = "null"
value_in_acting_version(m::ChunkHeaderMessageMetadata) = sbe_acting_version(m) >= 0
value_id(::ChunkHeaderMessageMetadata) = 4
value_header_length(::ChunkHeaderMessageMetadata) = 4

@inline function value_length(m::ChunkHeaderMessageMetadata)
    return decode_le(UInt32, m.buffer, sbe_position(m))
end

@inline function value_length!(m::ChunkHeaderMessageMetadataEncoder, n)
    @boundscheck n > 1073741824 && throw(ArgumentError("length exceeds schema limit"))
    @boundscheck checkbounds(m.buffer, sbe_position(m) + 4 + n)
    return encode_le(UInt32, m.buffer, sbe_position(m), n)
end

@inline function skip_value!(m::ChunkHeaderMessageMetadataDecoder)
    len = value_length(m)
    pos = sbe_position(m) + 4
    sbe_position!(m, pos + len)
    return len
end

@inline function value(m::ChunkHeaderMessageMetadataDecoder)
    len = value_length(m)
    pos = sbe_position(m) + 4
    sbe_position!(m, pos + len)
    return view(m.buffer, pos+1:pos+len)
end

@inline value(m::ChunkHeaderMessageMetadataDecoder, ::Type{AbstractArray{T}}) where {T<:Real} = reinterpret(T, value(m))
@inline value(m::ChunkHeaderMessageMetadataDecoder, ::Type{NTuple{N,T}}) where {N,T<:Real} = (x = reinterpret(T, value(m)); ntuple(i -> x[i], Val(N)))
@inline value(m::ChunkHeaderMessageMetadataDecoder, ::Type{T}) where {T<:AbstractString} = StringView(rstrip_nul(value(m)))
@inline value(m::ChunkHeaderMessageMetadataDecoder, ::Type{T}) where {T<:Symbol} = Symbol(value(m, StringView))
@inline value(m::ChunkHeaderMessageMetadataDecoder, ::Type{T}) where {T<:Real} = reinterpret(T, value(m))[]
@inline value(m::ChunkHeaderMessageMetadataDecoder, ::Type{T}) where {T<:Nothing} = (skip_value!(m); nothing)

@inline function value_buffer!(m::ChunkHeaderMessageMetadataEncoder, len)
    value_length!(m, len)
    pos = sbe_position(m) + 4
    sbe_position!(m, pos + len)
    return view(m.buffer, pos+1:pos+len)
end

@inline function value!(m::ChunkHeaderMessageMetadataEncoder, src::AbstractArray)
    len = sizeof(src)
    value_length!(m, len)
    pos = sbe_position(m) + 4
    sbe_position!(m, pos + len)
    dest = view(m.buffer, pos+1:pos+len)
    copyto!(dest, reinterpret(UInt8, src))
end

@inline function value!(m::ChunkHeaderMessageMetadataEncoder, src::NTuple)
    len = sizeof(src)
    value_length!(m, len)
    pos = sbe_position(m) + 4
    sbe_position!(m, pos + len)
    dest = view(m.buffer, pos+1:pos+len)
    copyto!(dest, reinterpret(NTuple{len,UInt8}, src))
end

@inline function value!(m::ChunkHeaderMessageMetadataEncoder, src::AbstractString)
    len = sizeof(src)
    value_length!(m, len)
    pos = sbe_position(m) + 4
    sbe_position!(m, pos + len)
    dest = view(m.buffer, pos+1:pos+len)
    copyto!(dest, codeunits(src))
end

@inline value!(m::ChunkHeaderMessageMetadataEncoder, src::Symbol) = value!(m, to_string(src))
@inline value!(m::ChunkHeaderMessageMetadataEncoder, src::StaticString) = value!(m, Tuple(src))
@inline value!(m::ChunkHeaderMessageMetadataEncoder, src::Real) = value!(m, Tuple(src))
@inline value!(m::ChunkHeaderMessageMetadataEncoder, ::Nothing) = value_buffer!(m, 0)

function show(io::IO, writer::ChunkHeaderMessageMetadata{T}) where {T}
    println(io, "ChunkHeaderMessageMetadata view over a type $T")
    print(io, "format: ")
    print(io, format(writer))

    println(io)
    print(io, "key: ")
    print(io, key(writer, StringView))

    println(io)
    print(io, "value: ")
    print(io, skip_value!(writer))
    print(io, " bytes of raw data")

end

@inline function sbe_skip!(m::ChunkHeaderMessageMetadataDecoder)
    
    skip_key!(m)
    skip_value!(m)
    return
end

@inline function metadata(m::ChunkHeaderMessage)
    return ChunkHeaderMessageMetadataDecoder(m.buffer, sbe_position_ptr(m), sbe_acting_version(m))
end

@inline function metadata!(m::ChunkHeaderMessage, count)
    return ChunkHeaderMessageMetadataEncoder(m.buffer, count, sbe_position_ptr(m))
end
metadata_group_count!(m::ChunkHeaderMessageEncoder, count) = metadata!(m, count)
metadata_id(::ChunkHeaderMessage) = 12
metadata_since_version(::ChunkHeaderMessage) = 0
metadata_in_acting_version(m::ChunkHeaderMessage) = sbe_acting_version(m) >= 0

function show(io::IO, m::ChunkHeaderMessage{T}) where {T}
    println(io, "ChunkHeaderMessage view over a type $T")
    println(io, "SbeBlockLength: ", sbe_block_length(m))
    println(io, "SbeTemplateId:  ", sbe_template_id(m))
    println(io, "SbeSchemaId:    ", sbe_schema_id(m))
    println(io, "SbeSchemaVersion: ", sbe_schema_version(m))

    writer = ChunkHeaderMessageDecoder(sbe_buffer(m), sbe_offset(m), Ref(0),
        sbe_block_length(m), sbe_schema_version(m))
    print(io, "header: ")
    show(io, header(writer))

    println(io)
    print(io, "sequencenumber: ")
    print(io, sequencenumber(writer))

    println(io)
    print(io, "length: ")
    print(io, length(writer))

    println(io)
    println(io, "Metadata:")
    for group in metadata(writer)
        show(io, group)
        println(io)
    end
    nothing
end

@inline function sbe_skip!(m::ChunkHeaderMessageDecoder)
    sbe_rewind!(m)
    for group in metadata(m)
        sbe_skip!(group)
    end
    return
end
