# Generated SBE (Simple Binary Encoding) message codec
# Code generated by SBE. DO NOT EDIT.

@enumx T=SbeEnum Format::Int8 begin
    NOTHING = Int8(0)
    UINT8 = Int8(1)
    INT8 = Int8(2)
    UINT16 = Int8(3)
    INT16 = Int8(4)
    UINT32 = Int8(5)
    INT32 = Int8(6)
    UINT64 = Int8(7)
    INT64 = Int8(8)
    FLOAT32 = Int8(9)
    FLOAT64 = Int8(10)
    BOOLEAN = Int8(11)
    STRING = Int8(12)
    BYTES = Int8(13)
    BIT = Int8(14)
    SBE = Int8(15)
    NULL_VALUE = Int8(-128)
end
