# Generated SBE (Simple Binary Encoding) message codec
# Code generated by SBE. DO NOT EDIT.

@enumx T=SbeEnum Indexing::Int8 begin
    ZERO = Int8(0)
    ONE = Int8(1)
    NULL_VALUE = Int8(-128)
end
