# Generated SBE (Simple Binary Encoding) message codec
# Code generated by SBE. DO NOT EDIT.

@enumx T=SbeEnum MajorOrder::Int8 begin
    ROW = Int8(0)
    COLUMN = Int8(1)
    NULL_VALUE = Int8(-128)
end
