# Generated SBE (Simple Binary Encoding) message codec
# Code generated by SBE. DO NOT EDIT.

export TensorStreamHeaderMessage, TensorStreamHeaderMessageDecoder, TensorStreamHeaderMessageEncoder
abstract type TensorStreamHeaderMessage{T} end

struct TensorStreamHeaderMessageDecoder{T<:AbstractArray{UInt8}} <: TensorStreamHeaderMessage{T}
    buffer::T
    offset::Int64
    position_ptr::Base.RefValue{Int64}
    acting_block_length::UInt16
    acting_version::UInt16
    function TensorStreamHeaderMessageDecoder(buffer::T, offset::Integer, position_ptr::Ref{Int64},
        acting_block_length::Integer, acting_version::Integer) where {T}
        position_ptr[] = offset + acting_block_length
        new{T}(buffer, offset, position_ptr, acting_block_length, acting_version)
    end
end

struct TensorStreamHeaderMessageEncoder{T<:AbstractArray{UInt8}} <: TensorStreamHeaderMessage{T}
    buffer::T
    offset::Int64
    position_ptr::Base.RefValue{Int64}
    function TensorStreamHeaderMessageEncoder(buffer::T, offset::Integer, position_ptr::Ref{Int64}) where {T}
        position_ptr[] = offset + 76
        new{T}(buffer, offset, position_ptr)
    end
end

@inline function TensorStreamHeaderMessageDecoder(buffer::AbstractArray, offset::Integer=0;
    position_ptr::Base.RefValue{Int64}=Ref(0),
    header::MessageHeader=MessageHeader(buffer, offset))
    if templateId(header) != UInt16(0xe) || schemaId(header) != UInt16(0x1)
        error("Template id or schema id mismatch")
    end
    TensorStreamHeaderMessageDecoder(buffer, offset + sbe_encoded_length(header), position_ptr,
        blockLength(header), version(header))
end
@inline function TensorStreamHeaderMessageEncoder(buffer::AbstractArray, offset::Integer=0;
    position_ptr::Base.RefValue{Int64}=Ref(0),
    header::MessageHeader=MessageHeader(buffer, offset))
    blockLength!(header, UInt16(0x4c))
    templateId!(header, UInt16(0xe))
    schemaId!(header, UInt16(0x1))
    version!(header, UInt16(0x0))
    TensorStreamHeaderMessageEncoder(buffer, offset + sbe_encoded_length(header), position_ptr)
end
sbe_buffer(m::TensorStreamHeaderMessage) = m.buffer
sbe_offset(m::TensorStreamHeaderMessage) = m.offset
sbe_position_ptr(m::TensorStreamHeaderMessage) = m.position_ptr
sbe_position(m::TensorStreamHeaderMessage) = m.position_ptr[]
sbe_position!(m::TensorStreamHeaderMessage, position) = m.position_ptr[] = position
sbe_block_length(::TensorStreamHeaderMessage) = UInt16(0x4c)
sbe_block_length(::Type{<:TensorStreamHeaderMessage}) = UInt16(0x4c)
sbe_template_id(::TensorStreamHeaderMessage) = UInt16(0xe)
sbe_template_id(::Type{<:TensorStreamHeaderMessage})  = UInt16(0xe)
sbe_schema_id(::TensorStreamHeaderMessage) = UInt16(0x1)
sbe_schema_id(::Type{<:TensorStreamHeaderMessage})  = UInt16(0x1)
sbe_schema_version(::TensorStreamHeaderMessage) = UInt16(0x0)
sbe_schema_version(::Type{<:TensorStreamHeaderMessage})  = UInt16(0x0)
sbe_semantic_type(::TensorStreamHeaderMessage) = ""
sbe_semantic_version(::TensorStreamHeaderMessage) = ""
sbe_acting_block_length(m::TensorStreamHeaderMessageDecoder) = m.acting_block_length
sbe_acting_block_length(::TensorStreamHeaderMessageEncoder) = UInt16(0x4c)
sbe_acting_version(m::TensorStreamHeaderMessageDecoder) = m.acting_version
sbe_acting_version(::TensorStreamHeaderMessageEncoder) = UInt16(0x0)
sbe_rewind!(m::TensorStreamHeaderMessage) = sbe_position!(m, m.offset + sbe_acting_block_length(m))
sbe_encoded_length(m::TensorStreamHeaderMessage) = sbe_position(m) - m.offset
@inline function sbe_decoded_length(m::TensorStreamHeaderMessage)
    skipper = TensorStreamHeaderMessageDecoder(sbe_buffer(m), sbe_offset(m), Ref(0),
        sbe_acting_block_length(m), sbe_acting_version(m))
    sbe_skip!(skipper)
    sbe_encoded_length(skipper)
end

function header_meta_attribute(::TensorStreamHeaderMessage, meta_attribute)
    meta_attribute === :presence && return Symbol("required")
    return Symbol("")
end
header_id(::TensorStreamHeaderMessage) = UInt16(0x1)
header_since_version(::TensorStreamHeaderMessage) = UInt16(0x0)
header_in_acting_version(m::TensorStreamHeaderMessage) = sbe_acting_version(m) >= UInt16(0x0)
header_encoding_offset(::TensorStreamHeaderMessage) = 0
header(m::TensorStreamHeaderMessage) = SpidersMessageHeader(m.buffer, m.offset + 0, sbe_acting_version(m))

function sequencenumber_meta_attribute(::TensorStreamHeaderMessage, meta_attribute)
    meta_attribute === :presence && return Symbol("required")
    return Symbol("")
end
sequencenumber_id(::TensorStreamHeaderMessage) = UInt16(0x2)
sequencenumber_since_version(::TensorStreamHeaderMessage) = UInt16(0x0)
sequencenumber_in_acting_version(m::TensorStreamHeaderMessage) = sbe_acting_version(m) >= UInt16(0x0)
sequencenumber_encoding_offset(::TensorStreamHeaderMessage) = 64
sequencenumber_null_value(::TensorStreamHeaderMessage) = Int64(-9223372036854775808)
sequencenumber_min_value(::TensorStreamHeaderMessage) = Int64(-9223372036854775807)
sequencenumber_max_value(::TensorStreamHeaderMessage) = Int64(9223372036854775807)
sequencenumber_encoding_length(::TensorStreamHeaderMessage) = 8

@inline function sequencenumber(m::TensorStreamHeaderMessageDecoder)
    return decode_le(Int64, m.buffer, m.offset + 64)
end
@inline sequencenumber!(m::TensorStreamHeaderMessageEncoder, value) = encode_le(Int64, m.buffer, m.offset + 64, value)

function format_meta_attribute(::TensorStreamHeaderMessage, meta_attribute)
    meta_attribute === :presence && return Symbol("required")
    return Symbol("")
end
format_id(::TensorStreamHeaderMessage) = UInt16(0x3)
format_since_version(::TensorStreamHeaderMessage) = UInt16(0x0)
format_in_acting_version(m::TensorStreamHeaderMessage) = sbe_acting_version(m) >= UInt16(0x0)
format_encoding_offset(::TensorStreamHeaderMessage) = 72
format_encoding_length(::TensorStreamHeaderMessage) = 1
@inline function format(::Type{Integer}, m::TensorStreamHeaderMessageDecoder)
    return decode_le(Int8, m.buffer, m.offset + 72)
end
@inline function format(m::TensorStreamHeaderMessageDecoder)
    return Format.SbeEnum(decode_le(Int8, m.buffer, m.offset + 72))
end
@inline format!(m::TensorStreamHeaderMessageEncoder, value::Format.SbeEnum) = encode_le(Int8, m.buffer, m.offset + 72, Int8(value))

function order_meta_attribute(::TensorStreamHeaderMessage, meta_attribute)
    meta_attribute === :presence && return Symbol("required")
    return Symbol("")
end
order_id(::TensorStreamHeaderMessage) = UInt16(0x4)
order_since_version(::TensorStreamHeaderMessage) = UInt16(0x0)
order_in_acting_version(m::TensorStreamHeaderMessage) = sbe_acting_version(m) >= UInt16(0x0)
order_encoding_offset(::TensorStreamHeaderMessage) = 73
order_encoding_length(::TensorStreamHeaderMessage) = 1
@inline function order(::Type{Integer}, m::TensorStreamHeaderMessageDecoder)
    return decode_le(Int8, m.buffer, m.offset + 73)
end
@inline function order(m::TensorStreamHeaderMessageDecoder)
    return MajorOrder.SbeEnum(decode_le(Int8, m.buffer, m.offset + 73))
end
@inline order!(m::TensorStreamHeaderMessageEncoder, value::MajorOrder.SbeEnum) = encode_le(Int8, m.buffer, m.offset + 73, Int8(value))

function reserved1_meta_attribute(::TensorStreamHeaderMessage, meta_attribute)
    meta_attribute === :presence && return Symbol("required")
    return Symbol("")
end
reserved1_id(::TensorStreamHeaderMessage) = UInt16(0x5)
reserved1_since_version(::TensorStreamHeaderMessage) = UInt16(0x0)
reserved1_in_acting_version(m::TensorStreamHeaderMessage) = sbe_acting_version(m) >= UInt16(0x0)
reserved1_encoding_offset(::TensorStreamHeaderMessage) = 74
reserved1_null_value(::TensorStreamHeaderMessage) = Int8(-128)
reserved1_min_value(::TensorStreamHeaderMessage) = Int8(-127)
reserved1_max_value(::TensorStreamHeaderMessage) = Int8(127)
reserved1_encoding_length(::TensorStreamHeaderMessage) = 2
reserved1_length(::TensorStreamHeaderMessage) = 2
reserved1_eltype(::TensorStreamHeaderMessage) = Int8

@inline function reserved1(m::TensorStreamHeaderMessageDecoder)
    return mappedarray(ltoh, reinterpret(Int8, view(m.buffer, m.offset+74+1:m.offset+74+sizeof(Int8)*2)))
end

@inline function reserved1(::Type{<:SVector},m::TensorStreamHeaderMessageDecoder)
    return mappedarray(ltoh, reinterpret(SVector{2,Int8}, view(m.buffer, m.offset+74+1:m.offset+74+sizeof(Int8)*2))[])
end

@inline function reserved1!(m::TensorStreamHeaderMessageEncoder)
    return mappedarray(ltoh, htol, reinterpret(Int8, view(m.buffer, m.offset+74+1:m.offset+74+sizeof(Int8)*2)))
end

@inline function reserved1!(m::TensorStreamHeaderMessageEncoder, value)
    copyto!(reserved1!(m), value)
end

export Slice, SliceDecoder, SliceEncoder
abstract type Slice{T} end

mutable struct SliceDecoder{T<:AbstractArray{UInt8}} <: Slice{T}
    const buffer::T
    offset::Int64
    const position_ptr::Base.RefValue{Int64}
    const block_length::UInt16
    const acting_version::UInt16
    const count::UInt16
    index::UInt16
    function SliceDecoder(buffer::T, offset::Integer, position_ptr::Ref{Int64},
        block_length::Integer, acting_version::Integer,
        count::Integer, index::Integer) where {T}
        new{T}(buffer, offset, position_ptr, block_length, acting_version, count, index)
    end
end

mutable struct SliceEncoder{T<:AbstractArray{UInt8}} <: Slice{T}
    const buffer::T
    offset::Int64
    const position_ptr::Base.RefValue{Int64}
    const initial_position::Int64
    const count::UInt16
    index::UInt16
    function SliceEncoder(buffer::T, offset::Integer, position_ptr::Ref{Int64},
        initial_position::Int64, count::Integer, index::Integer) where {T}
        new{T}(buffer, offset, position_ptr, initial_position, count, index)
    end
end

@inline function SliceDecoder(buffer, position_ptr, acting_version)
    dimensions = GroupSizeEncoding(buffer, position_ptr[])
    position_ptr[] += 4
    return SliceDecoder(buffer, 0, position_ptr, blockLength(dimensions),
        acting_version, numInGroup(dimensions), 0)
end

@inline function SliceEncoder(buffer, count, position_ptr)
    if count > 65534
        error("count outside of allowed range")
    end
    dimensions = GroupSizeEncoding(buffer, position_ptr[])
    blockLength!(dimensions, UInt16(0x8))
    numInGroup!(dimensions, count)
    initial_position = position_ptr[]
    position_ptr[] += 4
    return SliceEncoder(buffer, 0, position_ptr, initial_position, count, 0)
end

sbe_header_size(::Slice) = 4
sbe_block_length(::Slice) = UInt16(0x8)
sbe_acting_block_length(g::SliceDecoder) = g.block_length
sbe_acting_block_length(g::SliceEncoder) = UInt16(0x8)
sbe_acting_version(g::SliceDecoder) = g.acting_version
sbe_position(g::Slice) = g.position_ptr[]
@inline sbe_position!(g::Slice, position) = g.position_ptr[] = position
sbe_position_ptr(g::Slice) = g.position_ptr
@inline function next!(g::Slice)
    if g.index >= g.count
        error("index >= count")
    end
    g.offset = sbe_position(g)
    sbe_position!(g, g.offset + sbe_acting_block_length(g))
    g.index += 1
    return g
end
function Base.iterate(g::Slice, state=nothing)
    if g.index < g.count
        g.offset = sbe_position(g)
        sbe_position!(g, g.offset + sbe_acting_block_length(g))
        g.index += 1
        return g, state
    else
        return nothing
    end
end
Base.eltype(::Type{<:Slice}) = Slice
Base.isdone(g::Slice, state=nothing) = g.index >= g.count
Base.length(g::Slice) = g.count

function reset_count_to_index!(g::SliceEncoder)
    g.count = g.index
    dimensions = GroupSizeEncoding(g.buffer, g.initial_position)
    numInGroup!(dimensions, g.count)
    return g.count
end

function start_meta_attribute(::Slice, meta_attribute)
    meta_attribute === :presence && return Symbol("required")
    return Symbol("")
end
start_id(::Slice) = UInt16(0x1)
start_since_version(::Slice) = UInt16(0x0)
start_in_acting_version(m::Slice) = sbe_acting_version(m) >= UInt16(0x0)
start_encoding_offset(::Slice) = 0
start_null_value(::Slice) = Int32(-2147483648)
start_min_value(::Slice) = Int32(-2147483647)
start_max_value(::Slice) = Int32(2147483647)
start_encoding_length(::Slice) = 4

@inline function start(m::SliceDecoder)
    return decode_le(Int32, m.buffer, m.offset + 0)
end
@inline start!(m::SliceEncoder, value) = encode_le(Int32, m.buffer, m.offset + 0, value)

function stop_meta_attribute(::Slice, meta_attribute)
    meta_attribute === :presence && return Symbol("required")
    return Symbol("")
end
stop_id(::Slice) = UInt16(0x2)
stop_since_version(::Slice) = UInt16(0x0)
stop_in_acting_version(m::Slice) = sbe_acting_version(m) >= UInt16(0x0)
stop_encoding_offset(::Slice) = 4
stop_null_value(::Slice) = Int32(-2147483648)
stop_min_value(::Slice) = Int32(-2147483647)
stop_max_value(::Slice) = Int32(2147483647)
stop_encoding_length(::Slice) = 4

@inline function stop(m::SliceDecoder)
    return decode_le(Int32, m.buffer, m.offset + 4)
end
@inline stop!(m::SliceEncoder, value) = encode_le(Int32, m.buffer, m.offset + 4, value)

function show(io::IO, writer::Slice{T}) where {T}
    println(io, "Slice view over a type $T")
    print(io, "start: ")
    print(io, start(writer))

    println(io)
    print(io, "stop: ")
    print(io, stop(writer))

end

@inline function sbe_skip!(m::SliceDecoder)
    
    return
end

@inline function slice(m::TensorStreamHeaderMessage)
    return SliceDecoder(m.buffer, sbe_position_ptr(m), sbe_acting_version(m))
end

@inline function slice!(m::TensorStreamHeaderMessage, count)
    return SliceEncoder(m.buffer, count, sbe_position_ptr(m))
end
slice_group_count!(m::TensorStreamHeaderMessageEncoder, count) = slice!(m, count)
slice_id(::TensorStreamHeaderMessage) = 11
slice_since_version(::TensorStreamHeaderMessage) = 0
slice_in_acting_version(m::TensorStreamHeaderMessage) = sbe_acting_version(m) >= 0

export Metadata, MetadataDecoder, MetadataEncoder
abstract type Metadata{T} end

mutable struct MetadataDecoder{T<:AbstractArray{UInt8}} <: Metadata{T}
    const buffer::T
    offset::Int64
    const position_ptr::Base.RefValue{Int64}
    const block_length::UInt16
    const acting_version::UInt16
    const count::UInt16
    index::UInt16
    function MetadataDecoder(buffer::T, offset::Integer, position_ptr::Ref{Int64},
        block_length::Integer, acting_version::Integer,
        count::Integer, index::Integer) where {T}
        new{T}(buffer, offset, position_ptr, block_length, acting_version, count, index)
    end
end

mutable struct MetadataEncoder{T<:AbstractArray{UInt8}} <: Metadata{T}
    const buffer::T
    offset::Int64
    const position_ptr::Base.RefValue{Int64}
    const initial_position::Int64
    const count::UInt16
    index::UInt16
    function MetadataEncoder(buffer::T, offset::Integer, position_ptr::Ref{Int64},
        initial_position::Int64, count::Integer, index::Integer) where {T}
        new{T}(buffer, offset, position_ptr, initial_position, count, index)
    end
end

@inline function MetadataDecoder(buffer, position_ptr, acting_version)
    dimensions = GroupSizeEncoding(buffer, position_ptr[])
    position_ptr[] += 4
    return MetadataDecoder(buffer, 0, position_ptr, blockLength(dimensions),
        acting_version, numInGroup(dimensions), 0)
end

@inline function MetadataEncoder(buffer, count, position_ptr)
    if count > 65534
        error("count outside of allowed range")
    end
    dimensions = GroupSizeEncoding(buffer, position_ptr[])
    blockLength!(dimensions, UInt16(0x5))
    numInGroup!(dimensions, count)
    initial_position = position_ptr[]
    position_ptr[] += 4
    return MetadataEncoder(buffer, 0, position_ptr, initial_position, count, 0)
end

sbe_header_size(::Metadata) = 4
sbe_block_length(::Metadata) = UInt16(0x5)
sbe_acting_block_length(g::MetadataDecoder) = g.block_length
sbe_acting_block_length(g::MetadataEncoder) = UInt16(0x5)
sbe_acting_version(g::MetadataDecoder) = g.acting_version
sbe_position(g::Metadata) = g.position_ptr[]
@inline sbe_position!(g::Metadata, position) = g.position_ptr[] = position
sbe_position_ptr(g::Metadata) = g.position_ptr
@inline function next!(g::Metadata)
    if g.index >= g.count
        error("index >= count")
    end
    g.offset = sbe_position(g)
    sbe_position!(g, g.offset + sbe_acting_block_length(g))
    g.index += 1
    return g
end
function Base.iterate(g::Metadata, state=nothing)
    if g.index < g.count
        g.offset = sbe_position(g)
        sbe_position!(g, g.offset + sbe_acting_block_length(g))
        g.index += 1
        return g, state
    else
        return nothing
    end
end
Base.eltype(::Type{<:Metadata}) = Metadata
Base.isdone(g::Metadata, state=nothing) = g.index >= g.count
Base.length(g::Metadata) = g.count

function reset_count_to_index!(g::MetadataEncoder)
    g.count = g.index
    dimensions = GroupSizeEncoding(g.buffer, g.initial_position)
    numInGroup!(dimensions, g.count)
    return g.count
end

function format_meta_attribute(::Metadata, meta_attribute)
    meta_attribute === :presence && return Symbol("required")
    return Symbol("")
end
format_id(::Metadata) = UInt16(0x1)
format_since_version(::Metadata) = UInt16(0x0)
format_in_acting_version(m::Metadata) = sbe_acting_version(m) >= UInt16(0x0)
format_encoding_offset(::Metadata) = 0
format_encoding_length(::Metadata) = 1
@inline function format(::Type{Integer}, m::MetadataDecoder)
    return decode_le(Int8, m.buffer, m.offset + 0)
end
@inline function format(m::MetadataDecoder)
    return Format.SbeEnum(decode_le(Int8, m.buffer, m.offset + 0))
end
@inline format!(m::MetadataEncoder, value::Format.SbeEnum) = encode_le(Int8, m.buffer, m.offset + 0, Int8(value))

function key_meta_attribute(::Metadata, meta_attribute)
    meta_attribute === :presence && return Symbol("required")
    return Symbol("")
end
key_id(::Metadata) = UInt16(0x3)
key_since_version(::Metadata) = UInt16(0x0)
key_in_acting_version(m::Metadata) = sbe_acting_version(m) >= UInt16(0x0)
key_encoding_offset(::Metadata) = 1
key(m::Metadata) = VarStringEncoding(m.buffer, m.offset + 1, sbe_acting_version(m))

function value_meta_attribute(::Metadata, meta_attribute)
    meta_attribute === :presence && return Symbol("required")
    return Symbol("")
end
value_id(::Metadata) = UInt16(0x4)
value_since_version(::Metadata) = UInt16(0x0)
value_in_acting_version(m::Metadata) = sbe_acting_version(m) >= UInt16(0x0)
value_encoding_offset(::Metadata) = 5
value(m::Metadata) = VarDataEncoding(m.buffer, m.offset + 5, sbe_acting_version(m))

function show(io::IO, writer::Metadata{T}) where {T}
    println(io, "Metadata view over a type $T")
    print(io, "format: ")
    print(io, format(writer))

    println(io)
    print(io, "key: ")
    show(io, key(writer))

end

@inline function sbe_skip!(m::MetadataDecoder)
    
    return
end

@inline function metadata(m::TensorStreamHeaderMessage)
    return MetadataDecoder(m.buffer, sbe_position_ptr(m), sbe_acting_version(m))
end

@inline function metadata!(m::TensorStreamHeaderMessage, count)
    return MetadataEncoder(m.buffer, count, sbe_position_ptr(m))
end
metadata_group_count!(m::TensorStreamHeaderMessageEncoder, count) = metadata!(m, count)
metadata_id(::TensorStreamHeaderMessage) = 12
metadata_since_version(::TensorStreamHeaderMessage) = 0
metadata_in_acting_version(m::TensorStreamHeaderMessage) = sbe_acting_version(m) >= 0

function dims_meta_attribute(::TensorStreamHeaderMessage, meta_attribute)
    meta_attribute === :semantic_type && return Symbol("int32")
    meta_attribute === :presence && return Symbol("required")
    return Symbol("")
end

dims_character_encoding(::TensorStreamHeaderMessage) = "null"
dims_in_acting_version(m::TensorStreamHeaderMessage) = sbe_acting_version(m) >= 0
dims_id(::TensorStreamHeaderMessage) = 10
dims_header_length(::TensorStreamHeaderMessage) = 4

@inline function dims_length(m::TensorStreamHeaderMessage)
    return decode_le(UInt32, m.buffer, sbe_position(m))
end

@inline function dims_length!(m::TensorStreamHeaderMessageEncoder, n)
    if !checkbounds(Bool, m.buffer, sbe_position(m) + 4 + n)
        error("buffer too short for data length")
    elseif n > 1073741824
        error("data length too large for length type")
    end
    return encode_le(UInt32, m.buffer, sbe_position(m), n)
end

@inline function skip_dims!(m::TensorStreamHeaderMessageDecoder)
    len = dims_length(m)
    pos = sbe_position(m) + 4
    sbe_position!(m, pos + len)
    return len
end

@inline function dims(m::TensorStreamHeaderMessageDecoder)
    len = dims_length(m)
    pos = sbe_position(m) + 4
    sbe_position!(m, pos + len)
    return view(m.buffer, pos+1:pos+len)
end

dims(::Type{<:AbstractString}, m::TensorStreamHeaderMessageDecoder) = StringView(rstrip_nul(dims(m)))
dims(::Type{<:Symbol}, m::TensorStreamHeaderMessageDecoder) = Symbol(dims(StringView, m))

@inline function dims!(m::TensorStreamHeaderMessageEncoder; length::Int64)
    dims_length!(m, length)
    pos = sbe_position(m) + 4
    sbe_position!(m, pos + length)
    return view(m.buffer, pos+1:pos+length)
end

@inline function dims!(m::TensorStreamHeaderMessageEncoder, src::AbstractArray)
    len = sizeof(src)
    dims_length!(m, len)
    pos = sbe_position(m) + 4
    sbe_position!(m, pos + len)
    dest = view(m.buffer, pos+1:pos+len)
    copyto!(dest, reinterpret(UInt8, src))
end

@inline function dims!(m::TensorStreamHeaderMessageEncoder, src::NTuple{N,T}) where {N,T}
    len = sizeof(src)
    dims_length!(m, len)
    pos = sbe_position(m) + 4
    sbe_position!(m, pos + len)
    dest = view(m.buffer, pos+1:pos+len)
    copyto!(dest, reinterpret(NTuple{N * sizeof(T),UInt8}, src))
end

@inline function dims!(m::TensorStreamHeaderMessageEncoder, src::AbstractString)
    len = sizeof(src)
    dims_length!(m, len)
    pos = sbe_position(m) + 4
    sbe_position!(m, pos + len)
    dest = view(m.buffer, pos+1:pos+len)
    copyto!(dest, transcode(UInt8, src))
end

dims!(m::TensorStreamHeaderMessageEncoder, src::Symbol) = dims!(m, to_string(src))

function show(io::IO, m::TensorStreamHeaderMessage{T}) where {T}
    println(io, "TensorStreamHeaderMessage view over a type $T")
    println(io, "SbeBlockLength: ", sbe_block_length(m))
    println(io, "SbeTemplateId:  ", sbe_template_id(m))
    println(io, "SbeSchemaId:    ", sbe_schema_id(m))
    println(io, "SbeSchemaVersion: ", sbe_schema_version(m))

    writer = TensorStreamHeaderMessageDecoder(sbe_buffer(m), sbe_offset(m), Ref(0),
        sbe_block_length(m), sbe_schema_version(m))
    print(io, "header: ")
    show(io, header(writer))

    println(io)
    print(io, "sequencenumber: ")
    print(io, sequencenumber(writer))

    println(io)
    print(io, "format: ")
    print(io, format(writer))

    println(io)
    print(io, "order: ")
    print(io, order(writer))

    println(io)
    print(io, "reserved1: ")
    print(io, reserved1(writer))

    println(io)
    println(io, "Slice:")
    for group in slice(writer)
        show(io, group)
        println(io)
    end
    println(io)
    println(io, "Metadata:")
    for group in metadata(writer)
        show(io, group)
        println(io)
    end
    println(io)
    print(io, "dims: ")
    print(io, skip_dims!(writer))
    print(io, " bytes of raw data")

    nothing
end

@inline function sbe_skip!(m::TensorStreamHeaderMessageDecoder)
    sbe_rewind!(m)
    for group in slice(m)
        sbe_skip!(group)
    end
    for group in metadata(m)
        sbe_skip!(group)
    end
    skip_dims!(m)
    return
end
