# Generated SBE (Simple Binary Encoding) message codec
# Code generated by SBE. DO NOT EDIT.

@inline function encode_le(::Type{T}, buffer, offset, value) where {T}
    @inbounds reinterpret(T, view(buffer, offset+1:offset+sizeof(T)))[] = htol(value)
end

@inline function encode_be(::Type{T}, buffer, offset, value) where {T}
    @inbounds reinterpret(T, view(buffer, offset+1:offset+sizeof(T)))[] = hton(value)
end

@inline function decode_le(::Type{T}, buffer, offset) where {T}
    @inbounds ltoh(reinterpret(T, view(buffer, offset+1:offset+sizeof(T)))[])
end

@inline function decode_be(::Type{T}, buffer, offset) where {T}
    @inbounds ntoh(reinterpret(T, view(buffer, offset+1:offset+sizeof(T)))[])
end

@inline function rstrip_nul(a::Union{AbstractString,AbstractArray})
    pos = findfirst(iszero, a)
    len = pos !== nothing ? pos - 1 : Base.length(a)
    return view(a, 1:len)
end

